/**
 * Generated by Sybase AFX Compiler with templateJ
 * Compiler version - 2.3.0.183
 * mbs - false 
 */  
package ru.terralink.mvideo.sap.intrnl;

@SuppressWarnings("all")
public class LocalKeyGeneratorMetaData extends com.sybase.reflection.EntityMetaDataEx
{
    /**
     * Sybase internal use only.
     */
    public LocalKeyGeneratorMetaData()
    {
        super(ru.terralink.mvideo.sap.Mvideo5DB.getMetaData());
        _init();
    }
    protected void _init()
    {
        setId(17);
        setAttributes(new com.sybase.reflection.AttributeMetaDataList());
        setAttributeMap(new com.sybase.reflection.AttributeMap());
        com.sybase.reflection.AttributeMetaData firstId_attribute = addAttributeWithParams
        	(1218, "firstId", "long", 
        	-1, 
        	false, false, true, false, false, 
        	false,false, 
        	"\"first_id\"", "bigint", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData lastId_attribute = addAttributeWithParams
        	(1219, "lastId", "long", 
        	-1, 
        	false, false, true, false, false, 
        	false,false, 
        	"\"last_id\"", "bigint", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData nextId_attribute = addAttributeWithParams
        	(1220, "nextId", "long", 
        	-1, 
        	false, false, true, false, false, 
        	false,false, 
        	"\"next_id\"", "bigint", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData remoteId_attribute = addAttributeWithParams
        	(1216, "remoteId", "string", 
        	300, 
        	false, true, true, false, false, 
        	false,false, 
        	"\"remote_id\"", "varchar(300)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData batchId_attribute = addAttributeWithParams
        	(1217, "batchId", "long", 
        	-1, 
        	false, true, true, false, false, 
        	false,false, 
        	"\"batch_id\"", "bigint", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        initAttributeMapFromAttributes();
        setName("LocalKeyGenerator");
        setTable("\"co_mvideo5_1_0_localkeygenerator\"");
        setSynchronizationGroup("");
        this.getKeyAttributes().add((remoteId_attribute));
        this.getKeyAttributes().add((batchId_attribute));
        this.setKeyClass("LocalKeyGeneratorPK");
    }
    
    /**
     * Sybase internal use only.
     */
    public  boolean isEntity()
    {
        return true;
    }
    
    /**
     * Sybase internal use only.
     */
    public  boolean isService()
    {
        return false;
    }
}