/**
 * Generated by Sybase AFX Compiler with templateJ
 * Compiler version - 2.3.0.183
 * mbs - false 
 */  
package ru.terralink.mvideo.sap.intrnl;

@SuppressWarnings("all")
public class OperDaySynchronizationParametersMetaData extends com.sybase.reflection.EntityMetaDataEx
{
    /**
     * Sybase internal use only.
     */
    public OperDaySynchronizationParametersMetaData()
    {
        super(ru.terralink.mvideo.sap.Mvideo5DB.getMetaData());
        _init();
    }
    protected void _init()
    {
        setId(15);
        setAttributes(new com.sybase.reflection.AttributeMetaDataList());
        setAttributeMap(new com.sybase.reflection.AttributeMap());
        com.sybase.reflection.AttributeMetaData sp_date_attribute = addAttributeWithParams
        	(511, "sp_date", "date?", 
        	-1, 
        	false, false, true, false, false, 
        	false,false, 
        	"\"sp_date\"", "date", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "2014-04-23", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, true, false);
        com.sybase.reflection.AttributeMetaData sp_dateUserDefined_attribute = addAttributeWithParams
        	(512, "sp_dateUserDefined", "boolean", 
        	-1, 
        	false, false, true, false, false, 
        	false,false, 
        	"\"sp_dateUserDefined\"", "tinyint", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "false", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData sp_numb_attribute = addAttributeWithParams
        	(513, "sp_numb", "string?", 
        	20, 
        	false, false, true, false, false, 
        	false,false, 
        	"\"sp_numb\"", "varchar(80)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, true, false);
        com.sybase.reflection.AttributeMetaData sp_numbUserDefined_attribute = addAttributeWithParams
        	(514, "sp_numbUserDefined", "boolean", 
        	-1, 
        	false, false, true, false, false, 
        	false,false, 
        	"\"sp_numbUserDefined\"", "tinyint", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "false", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData size_sp_attribute = addAttributeWithParams
        	(516, "size_sp", "int", 
        	-1, 
        	false, false, true, false, false, 
        	false,false, 
        	"\"size_sp\"", "integer", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "2", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData user_sp_attribute = addAttributeWithParams
        	(515, "user_sp", "string", 
        	300, 
        	false, true, true, false, false, 
        	false,false, 
        	"\"user_sp\"", "varchar(300)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        initAttributeMapFromAttributes();
        setName("OperDaySynchronizationParameters");
        setSuperClassDefined(true);
        setTable("\"co_mvideo5_1_0_operdaysp\"");
        setSynchronizationGroup("");
        this.getKeyAttributes().add((user_sp_attribute));
    }
    
    /**
     * Sybase internal use only.
     */
    public  boolean isEntity()
    {
        return true;
    }
    
    /**
     * Sybase internal use only.
     */
    public  boolean isService()
    {
        return false;
    }
}