/**
 * Generated by Sybase AFX Compiler with templateJ
 * Compiler version - 2.3.0.183
 * mbs - false 
 */  
package ru.terralink.mvideo.sap.intrnl;

@SuppressWarnings("all")
public class OperDay_pull_pqMetaData extends com.sybase.reflection.EntityMetaDataEx
{
    /**
     * Sybase internal use only.
     */
    public OperDay_pull_pqMetaData()
    {
        super(ru.terralink.mvideo.sap.Mvideo5DB.getMetaData());
        _init();
    }
    protected void _init()
    {
        setId(4);
        setAttributes(new com.sybase.reflection.AttributeMetaDataList());
        setAttributeMap(new com.sybase.reflection.AttributeMap());
        com.sybase.reflection.AttributeMetaData username_attribute = addAttributeWithParams
        	(524, "username", "string?", 
        	300, 
        	false, false, true, false, false, 
        	false,false, 
        	"\"username\"", "varchar(300)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData remoteId_attribute = addAttributeWithParams
        	(525, "remoteId", "string?", 
        	300, 
        	false, false, true, false, false, 
        	false,false, 
        	"\"remoteId\"", "varchar(300)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData sp_dateParam_attribute = addAttributeWithParams
        	(528, "sp_dateParam", "date?", 
        	-1, 
        	false, false, true, false, false, 
        	false,false, 
        	"\"sp_dateParam\"", "date", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "2014-04-23", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, true, false);
        com.sybase.reflection.AttributeMetaData sp_numbParam_attribute = addAttributeWithParams
        	(529, "sp_numbParam", "string?", 
        	20, 
        	false, false, true, false, false, 
        	false,false, 
        	"\"sp_numbParam\"", "varchar(80)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, true, false);
        com.sybase.reflection.AttributeMetaData id_attribute = addAttributeWithParams
        	(523, "id", "long", 
        	-1, 
        	false, true, true, false, false, 
        	false,false, 
        	"\"id\"", "bigint", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.LOCAL,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        initAttributeMapFromAttributes();
        setName("OperDay_pull_pq");
        setSuperClassDefined(true);
        setTable("\"mvideo5_1_0_operday_pull_pq\"");
        setSynchronizationGroup("unsubscribe");
        com.sybase.reflection.IndexMetaData remoteId_index = new com.sybase.reflection.IndexMetaData();
        remoteId_index.setName("remoteId");
        remoteId_index.getAttributes().add(remoteId_attribute);
        this.getIndice().add(remoteId_index);
        com.sybase.reflection.IndexMetaData param_pull_index_index = new com.sybase.reflection.IndexMetaData();
        param_pull_index_index.setName("param_pull_index");
        param_pull_index_index.getAttributes().add(sp_dateParam_attribute);
        param_pull_index_index.getAttributes().add(sp_numbParam_attribute);
        this.getIndice().add(param_pull_index_index);
        this.getKeyAttributes().add((id_attribute));
    }
    
    /**
     * Sybase internal use only.
     */
    public  boolean isEntity()
    {
        return true;
    }
    
    /**
     * Sybase internal use only.
     */
    public  boolean isService()
    {
        return false;
    }
}