/**
 * Generated by Sybase AFX Compiler with templateJ
 * Compiler version - 2.3.0.183
 * mbs - false 
 */  
package ru.terralink.mvideo.sap.intrnl;

@SuppressWarnings("all")
public class SISSubscriptionMetaData extends com.sybase.reflection.EntityMetaDataEx
{
    /**
     * Sybase internal use only.
     */
    public SISSubscriptionMetaData()
    {
        super(ru.terralink.mvideo.sap.Mvideo5DB.getMetaData());
        _init();
    }
    protected void _init()
    {
        setId(10);
        setAttributes(new com.sybase.reflection.AttributeMetaDataList());
        setAttributeMap(new com.sybase.reflection.AttributeMap());
        com.sybase.reflection.AttributeMetaData deviceId_attribute = addAttributeWithParams
        	(432, "deviceId", "string", 
        	200, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"device_id\"", "varchar(200)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData username_attribute = addAttributeWithParams
        	(433, "username", "string", 
        	100, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"user_name\"", "varchar(100)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData appname_attribute = addAttributeWithParams
        	(434, "appname", "string", 
        	100, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"h\"", "varchar(100)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "sup", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData enable_attribute = addAttributeWithParams
        	(435, "enable", "boolean", 
        	-1, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"i\"", "tinyint", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "false", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData adminLock_attribute = addAttributeWithParams
        	(436, "adminLock", "boolean", 
        	-1, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"admin_lock\"", "tinyint", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "false", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData interval_attribute = addAttributeWithParams
        	(437, "interval", "int", 
        	-1, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"l\"", "integer", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "0", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData protocol_attribute = addAttributeWithParams
        	(438, "protocol", "string", 
        	100, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"m\"", "varchar(100)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "TCN", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData address_attribute = addAttributeWithParams
        	(439, "address", "string?", 
        	300, 
        	false, false, false, false, false, 
        	false,false, 
        	"\"n\"", "varchar(300)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData domain_attribute = addAttributeWithParams
        	(428, "domain", "string", 
        	100, 
        	false, true, false, false, false, 
        	false,false, 
        	"\"domain\"", "varchar(100)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData package_attribute = addAttributeWithParams
        	(429, "package", "string", 
        	100, 
        	false, true, false, false, false, 
        	false,false, 
        	"\"pkg\"", "varchar(100)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData syncGroup_attribute = addAttributeWithParams
        	(430, "syncGroup", "string", 
        	100, 
        	false, true, false, false, false, 
        	false,false, 
        	"\"sync_group\"", "varchar(100)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData clientId_attribute = addAttributeWithParams
        	(431, "clientId", "string", 
        	100, 
        	false, true, false, false, false, 
        	false,false, 
        	"\"cid\"", "varchar(100)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        initAttributeMapFromAttributes();
        setName("SISSubscription");
        setSuperClassDefined(true);
        setTable("\"sup_sis_subscription\"");
        setSynchronizationGroup("system");
        this.getKeyAttributes().add((domain_attribute));
        this.getKeyAttributes().add((package_attribute));
        this.getKeyAttributes().add((syncGroup_attribute));
        this.getKeyAttributes().add((clientId_attribute));
        this.setKeyClass("SISSubscriptionKey");
    }
    
    /**
     * Sybase internal use only.
     */
    public  boolean isEntity()
    {
        return true;
    }
    
    /**
     * Sybase internal use only.
     */
    public  boolean isService()
    {
        return false;
    }
}