/**
 * Generated by Sybase AFX Compiler with templateJ
 * Compiler version - 2.3.0.183
 * mbs - false 
 */
package ru.terralink.mvideo.sap.intrnl;

@SuppressWarnings("all")
public  class SISSubscription extends com.sybase.sup.client.persistence.SISSubscription implements com.sybase.reflection.ClassWithMetaData
{
    /** Begin code region: MetaData **/
    private static ru.terralink.mvideo.sap.intrnl.SISSubscriptionMetaData META_DATA = new ru.terralink.mvideo.sap.intrnl.SISSubscriptionMetaData();
    
    /**
     * return MetaData object  
     */
    public com.sybase.reflection.ClassMetaData getClassMetaData()
    {
        return META_DATA;
    }
    
    /**
     * return MetaData object  
     */
    public static com.sybase.reflection.EntityMetaData getMetaData()
    {
        return META_DATA;
    }
    
    /** End code region: MetaData **/
    protected static com.sybase.sup.client.persistence.EntityDelegate DELEGATE = 
        com.sybase.sup.client.persistence.DelegateFactory.createEntityDelegate("SISSubscription", ru.terralink.mvideo.sap.intrnl.SISSubscription.class, "mvideo5.SISSubscription", META_DATA, ru.terralink.mvideo.sap.Mvideo5DB.getDelegate());
}