/**
 * Generated by Sybase AFX Compiler with templateJ
 * Compiler version - 2.3.0.183
 * mbs - false 
 */
package ru.terralink.mvideo.sap.intrnl;

@SuppressWarnings("all")
public  class SISSubscriptionKey extends com.sybase.sup.client.persistence.SISSubscriptionKey implements com.sybase.reflection.ClassWithMetaData
{
    private static ru.terralink.mvideo.sap.intrnl.SISSubscriptionKeyMetaData META_DATA = new ru.terralink.mvideo.sap.intrnl.SISSubscriptionKeyMetaData();
    
    /**
     * Return MetaData instance.  
     */
    public com.sybase.reflection.ClassMetaData getClassMetaData()
    {
        return META_DATA;
    }
    
    /**
     * Return MetaData instance.  
     */
    public static com.sybase.reflection.ClassMetaData getMetaData()
    {
        return META_DATA;
    }
    protected static com.sybase.sup.client.persistence.ClassDelegate DELEGATE = 
        new com.sybase.sup.client.persistence.ClassDelegate("SISSubscriptionKey", ru.terralink.mvideo.sap.intrnl.SISSubscriptionKey.class, META_DATA, ru.terralink.mvideo.sap.Mvideo5DB.getDelegate());
}