/**
 * Generated by Sybase AFX Compiler with templateJ
 * Compiler version - 2.3.0.183
 * mbs - false 
 */  
package ru.terralink.mvideo.sap.intrnl;

@SuppressWarnings("all")
public class UpdateStatusSynchronizationParametersMetaData extends com.sybase.reflection.EntityMetaDataEx
{
    /**
     * Sybase internal use only.
     */
    public UpdateStatusSynchronizationParametersMetaData()
    {
        super(ru.terralink.mvideo.sap.Mvideo5DB.getMetaData());
        _init();
    }
    protected void _init()
    {
        setId(16);
        setAttributes(new com.sybase.reflection.AttributeMetaDataList());
        setAttributeMap(new com.sybase.reflection.AttributeMap());
        com.sybase.reflection.AttributeMetaData sp_code_attribute = addAttributeWithParams
        	(556, "sp_code", "string?", 
        	20, 
        	false, false, true, false, false, 
        	false,false, 
        	"\"sp_code\"", "varchar(80)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, true, false);
        com.sybase.reflection.AttributeMetaData sp_codeUserDefined_attribute = addAttributeWithParams
        	(557, "sp_codeUserDefined", "boolean", 
        	-1, 
        	false, false, true, false, false, 
        	false,false, 
        	"\"sp_codeUserDefined\"", "tinyint", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "false", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData sp_comment_attribute = addAttributeWithParams
        	(558, "sp_comment", "string?", 
        	20, 
        	false, false, true, false, false, 
        	false,false, 
        	"\"sp_comment\"", "varchar(80)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, true, false);
        com.sybase.reflection.AttributeMetaData sp_commentUserDefined_attribute = addAttributeWithParams
        	(559, "sp_commentUserDefined", "boolean", 
        	-1, 
        	false, false, true, false, false, 
        	false,false, 
        	"\"sp_commentUserDefined\"", "tinyint", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "false", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData sp_fo_attribute = addAttributeWithParams
        	(560, "sp_fo", "string?", 
        	20, 
        	false, false, true, false, false, 
        	false,false, 
        	"\"sp_fo\"", "varchar(80)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, true, false);
        com.sybase.reflection.AttributeMetaData sp_foUserDefined_attribute = addAttributeWithParams
        	(561, "sp_foUserDefined", "boolean", 
        	-1, 
        	false, false, true, false, false, 
        	false,false, 
        	"\"sp_foUserDefined\"", "tinyint", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "false", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData sp_fu_attribute = addAttributeWithParams
        	(562, "sp_fu", "string?", 
        	20, 
        	false, false, true, false, false, 
        	false,false, 
        	"\"sp_fu\"", "varchar(80)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, true, false);
        com.sybase.reflection.AttributeMetaData sp_fuUserDefined_attribute = addAttributeWithParams
        	(563, "sp_fuUserDefined", "boolean", 
        	-1, 
        	false, false, true, false, false, 
        	false,false, 
        	"\"sp_fuUserDefined\"", "tinyint", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "false", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData size_sp_attribute = addAttributeWithParams
        	(565, "size_sp", "int", 
        	-1, 
        	false, false, true, false, false, 
        	false,false, 
        	"\"size_sp\"", "integer", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "4", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData user_sp_attribute = addAttributeWithParams
        	(564, "user_sp", "string", 
        	300, 
        	false, true, true, false, false, 
        	false,false, 
        	"\"user_sp\"", "varchar(300)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        initAttributeMapFromAttributes();
        setName("UpdateStatusSynchronizationParameters");
        setSuperClassDefined(true);
        setTable("\"co_mvideo5_1_0_updatestatussp\"");
        setSynchronizationGroup("");
        this.getKeyAttributes().add((user_sp_attribute));
    }
    
    /**
     * Sybase internal use only.
     */
    public  boolean isEntity()
    {
        return true;
    }
    
    /**
     * Sybase internal use only.
     */
    public  boolean isService()
    {
        return false;
    }
}