/**
 * Generated by Sybase AFX Compiler with templateJ
 * Compiler version - 2.3.0.183
 * mbs - false 
 */  
package ru.terralink.mvideo.sap.intrnl;

@SuppressWarnings("all")
public class UpdateStatus_pull_pqMetaData extends com.sybase.reflection.EntityMetaDataEx
{
    /**
     * Sybase internal use only.
     */
    public UpdateStatus_pull_pqMetaData()
    {
        super(ru.terralink.mvideo.sap.Mvideo5DB.getMetaData());
        _init();
    }
    protected void _init()
    {
        setId(13);
        setAttributes(new com.sybase.reflection.AttributeMetaDataList());
        setAttributeMap(new com.sybase.reflection.AttributeMap());
        com.sybase.reflection.AttributeMetaData username_attribute = addAttributeWithParams
        	(573, "username", "string?", 
        	300, 
        	false, false, true, false, false, 
        	false,false, 
        	"\"username\"", "varchar(300)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData remoteId_attribute = addAttributeWithParams
        	(574, "remoteId", "string?", 
        	300, 
        	false, false, true, false, false, 
        	false,false, 
        	"\"remoteId\"", "varchar(300)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        com.sybase.reflection.AttributeMetaData sp_codeParam_attribute = addAttributeWithParams
        	(577, "sp_codeParam", "string?", 
        	20, 
        	false, false, true, false, false, 
        	false,false, 
        	"\"sp_codeParam\"", "varchar(80)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, true, false);
        com.sybase.reflection.AttributeMetaData sp_commentParam_attribute = addAttributeWithParams
        	(578, "sp_commentParam", "string?", 
        	20, 
        	false, false, true, false, false, 
        	false,false, 
        	"\"sp_commentParam\"", "varchar(80)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, true, false);
        com.sybase.reflection.AttributeMetaData sp_foParam_attribute = addAttributeWithParams
        	(579, "sp_foParam", "string?", 
        	20, 
        	false, false, true, false, false, 
        	false,false, 
        	"\"sp_foParam\"", "varchar(80)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, true, false);
        com.sybase.reflection.AttributeMetaData sp_fuParam_attribute = addAttributeWithParams
        	(580, "sp_fuParam", "string?", 
        	20, 
        	false, false, true, false, false, 
        	false,false, 
        	"\"sp_fuParam\"", "varchar(80)", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.NONE,
        	"", "", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, true, false);
        com.sybase.reflection.AttributeMetaData id_attribute = addAttributeWithParams
        	(572, "id", "long", 
        	-1, 
        	false, true, true, false, false, 
        	false,false, 
        	"\"id\"", "bigint", "", 0, 0, 
        	com.sybase.reflection.AttributeMetaData.GENERATED_SCHEME.LOCAL,
        	"", "null", com.sybase.reflection.PersonalizationMetaData.PersonalizationType.None,
        	false, false, false);
        initAttributeMapFromAttributes();
        setName("UpdateStatus_pull_pq");
        setSuperClassDefined(true);
        setTable("\"mvideo5_1_0_updatestatus_pull_pq\"");
        setSynchronizationGroup("unsubscribe");
        com.sybase.reflection.IndexMetaData remoteId_index = new com.sybase.reflection.IndexMetaData();
        remoteId_index.setName("remoteId");
        remoteId_index.getAttributes().add(remoteId_attribute);
        this.getIndice().add(remoteId_index);
        com.sybase.reflection.IndexMetaData param_pull_index_index = new com.sybase.reflection.IndexMetaData();
        param_pull_index_index.setName("param_pull_index");
        param_pull_index_index.getAttributes().add(sp_codeParam_attribute);
        param_pull_index_index.getAttributes().add(sp_commentParam_attribute);
        param_pull_index_index.getAttributes().add(sp_foParam_attribute);
        param_pull_index_index.getAttributes().add(sp_fuParam_attribute);
        this.getIndice().add(param_pull_index_index);
        this.getKeyAttributes().add((id_attribute));
    }
    
    /**
     * Sybase internal use only.
     */
    public  boolean isEntity()
    {
        return true;
    }
    
    /**
     * Sybase internal use only.
     */
    public  boolean isService()
    {
        return false;
    }
}