package ru.terralink.mvideo.sap;

/**
 * Generated by Sybase AFX Compiler with templateJ
 * Compiler version - 2.3.0.183
 * mbs - false 
 */
public abstract class EntityType
{
    public static int OperDay = 3;
    public static int Orders = 6;
    public static int Products = 8;
    public static int Relations = 9;
    public static int StatusesDict = 11;
    public static int UpdateStatus = 12;
}