/**
 * Generated by Sybase AFX Compiler with templateJ
 * Compiler version - 2.3.0.183
 * mbs - false 
 */
package ru.terralink.mvideo.sap;

@SuppressWarnings("all")
public  class OperDay extends com.sybase.persistence.AbstractEntity implements com.sybase.persistence.MobileBusinessObject, com.sybase.reflection.ClassWithMetaData
{
    /** Begin code region: MetaData **/
    private static ru.terralink.mvideo.sap.intrnl.OperDayMetaData META_DATA = new ru.terralink.mvideo.sap.intrnl.OperDayMetaData();
    
    /**
     * return MetaData object  
     */
    public com.sybase.reflection.ClassMetaData getClassMetaData()
    {
        return META_DATA;
    }
    
    /**
     * return MetaData object  
     */
    public static com.sybase.reflection.EntityMetaData getMetaData()
    {
        return META_DATA;
    }
    
    /** End code region: MetaData **/
    protected static com.sybase.sup.client.persistence.EntityDelegate DELEGATE = 
        com.sybase.sup.client.persistence.DelegateFactory.createEntityDelegate("OperDay", ru.terralink.mvideo.sap.OperDay.class, "mvideo5.OperDay", META_DATA, ru.terralink.mvideo.sap.Mvideo5DB.getDelegate());
    
    
    /** Begin code region: Properties **/
    private java.sql.Date __BEGDA ;  
    
    private java.lang.String __TOR_ID ;  
    
    private java.lang.String __ZNAME_ORG1 ;  
    
    private java.lang.String __ZNAME_ORG2 ;  
    
    private java.lang.String __ZDRIVER_NAME ;  
    
    private java.lang.String __ZDRIVER_PHONE ;  
    
    private java.lang.String __ZVEHICLE_NUMB ;  
    
    private java.lang.String __IV_VEHICLE_NUMB ;  
    
    private java.sql.Date __IV_BEGDA ;  
    
    private com.sybase.collections.GenericList<ru.terralink.mvideo.sap.Relations> __operDayRelations ;  
    
      
    
      
    
      
    
      
    
    private com.sybase.persistence.BigString __cvpOperation ;  
    
    private com.sybase.persistence.BigString __cvpOperationLobs ;  
    
    private long __surrogateKey ;  
    
      
    
      
    
    private long __cvpOperationLength ;  
    
    private long __cvpOperationLobsLength ;  
    
    public long getAttributeLong(int id)
    {
        switch(id)
        {
        case 62:
            return getSurrogateKey();
        case 1250:
            return getCvpOperationLength();
        case 1251:
            return getCvpOperationLobsLength();
        default:
            return super.getAttributeLong(id);
        }
    }
    
    public void setAttributeLong(int id, long v)
    {
        switch(id)
        {
        case 62:
            setSurrogateKey((long)v);
            break;
        case 1250:
            setCvpOperationLength((long)v);
            break;
        case 1251:
            setCvpOperationLobsLength((long)v);
            break;
        default:
            super.setAttributeLong(id, v);
            break;
        }
    }
    public com.sybase.persistence.BigString getAttributeNullableBigString(int id)
    {
        switch(id)
        {
        case 676:
            return getCvpOperation();
        case 677:
            return getCvpOperationLobs();
        default:
            return super.getAttributeNullableBigString(id);
        }
    }
    
    public java.lang.String getAttributeString(int id)
    {
        switch(id)
        {
        case 54:
            return getTOR_ID();
        case 55:
            return getZNAME_ORG1();
        case 56:
            return getZNAME_ORG2();
        case 57:
            return getZDRIVER_NAME();
        case 58:
            return getZDRIVER_PHONE();
        case 59:
            return getZVEHICLE_NUMB();
        case 60:
            return getIV_VEHICLE_NUMB();
        default:
            return super.getAttributeString(id);
        }
    }
    
    public void setAttributeString(int id, java.lang.String v)
    {
        switch(id)
        {
        case 54:
            setTOR_ID((java.lang.String)v);
            break;
        case 55:
            setZNAME_ORG1((java.lang.String)v);
            break;
        case 56:
            setZNAME_ORG2((java.lang.String)v);
            break;
        case 57:
            setZDRIVER_NAME((java.lang.String)v);
            break;
        case 58:
            setZDRIVER_PHONE((java.lang.String)v);
            break;
        case 59:
            setZVEHICLE_NUMB((java.lang.String)v);
            break;
        case 60:
            setIV_VEHICLE_NUMB((java.lang.String)v);
            break;
        default:
            super.setAttributeString(id, v);
            break;
        }
    }
    public java.sql.Date getAttributeNullableDate(int id)
    {
        switch(id)
        {
        case 53:
            return getBEGDA();
        case 61:
            return getIV_BEGDA();
        default:
            return super.getAttributeNullableDate(id);
        }
    }
    
    public void setAttributeNullableDate(int id, java.sql.Date v)
    {
        switch(id)
        {
        case 53:
            setBEGDA((java.sql.Date)v);
            break;
        case 61:
            setIV_BEGDA((java.sql.Date)v);
            break;
        default:
            super.setAttributeNullableDate(id, v);
            break;
        }
    }
    public java.lang.Object getAttributeObject(int id, boolean loadFromDBIfInvalid)
    {
        switch(id)
        {
        case 63:
            if(loadFromDBIfInvalid)
            {
                return getOperDayRelations();
            }
            else
            {
                return __operDayRelations;
            }
        default:
            return super.getAttributeObject(id);
        }
    }
    
    public void setAttributeObject(int id, java.lang.Object v)
    {
        switch(id)
        {
        case 63:
            setOperDayRelations((com.sybase.collections.GenericList<ru.terralink.mvideo.sap.Relations>)v);
            break;
        default:
            super.setAttributeObject(id, v);
            break;
        }
    }
    
    public Object getAttributeJson(int id)
    {
        switch(id)
        {
        default:
            return super.getAttributeJson(id);
        }
    }
    
    public void setAttributeJson(int id, Object value)
    {
        switch(id)
        {
        default:
            super.setAttributeJson(id, value);
            break;
        }
    }
    /** End code region: Properties **/
    
    /** Begin code region: Constructor and init **/
    /**
     * Creates an instance of ru.terralink.mvideo.sap.OperDay  
     */
    public OperDay()
    {
        setEntityDelegate(DELEGATE);
        _init();
    }
    protected void _init()
    {
        
    }
    /** End code region: Constructor and init **/
    
    /**
     * get the value of BEGDA  
     */
    public java.sql.Date getBEGDA()
    {
        
        return __BEGDA;
    }
    
    /**
     * Set the value of BEGDA  
     */
    public void setBEGDA(java.sql.Date value)
    {
        if ((__BEGDA == null) != (value == null) || (value != null && ! value.equals(__BEGDA)))
        {
            _isDirty = true;
        }
        __BEGDA = value;
    }       
    /**
     * get the value of TOR_ID  
     */
    public java.lang.String getTOR_ID()
    {
        
        return __TOR_ID;
    }
    
    /**
     * Set the value of TOR_ID  
     */
    public void setTOR_ID(java.lang.String value)
    {
        if ((__TOR_ID == null) != (value == null) || (value != null && ! value.equals(__TOR_ID)))
        {
            _isDirty = true;
        }
        __TOR_ID = value;
    }       
    /**
     * get the value of ZNAME_ORG1  
     */
    public java.lang.String getZNAME_ORG1()
    {
        
        return __ZNAME_ORG1;
    }
    
    /**
     * Set the value of ZNAME_ORG1  
     */
    public void setZNAME_ORG1(java.lang.String value)
    {
        if ((__ZNAME_ORG1 == null) != (value == null) || (value != null && ! value.equals(__ZNAME_ORG1)))
        {
            _isDirty = true;
        }
        __ZNAME_ORG1 = value;
    }       
    /**
     * get the value of ZNAME_ORG2  
     */
    public java.lang.String getZNAME_ORG2()
    {
        
        return __ZNAME_ORG2;
    }
    
    /**
     * Set the value of ZNAME_ORG2  
     */
    public void setZNAME_ORG2(java.lang.String value)
    {
        if ((__ZNAME_ORG2 == null) != (value == null) || (value != null && ! value.equals(__ZNAME_ORG2)))
        {
            _isDirty = true;
        }
        __ZNAME_ORG2 = value;
    }       
    /**
     * get the value of ZDRIVER_NAME  
     */
    public java.lang.String getZDRIVER_NAME()
    {
        
        return __ZDRIVER_NAME;
    }
    
    /**
     * Set the value of ZDRIVER_NAME  
     */
    public void setZDRIVER_NAME(java.lang.String value)
    {
        if ((__ZDRIVER_NAME == null) != (value == null) || (value != null && ! value.equals(__ZDRIVER_NAME)))
        {
            _isDirty = true;
        }
        __ZDRIVER_NAME = value;
    }       
    /**
     * get the value of ZDRIVER_PHONE  
     */
    public java.lang.String getZDRIVER_PHONE()
    {
        
        return __ZDRIVER_PHONE;
    }
    
    /**
     * Set the value of ZDRIVER_PHONE  
     */
    public void setZDRIVER_PHONE(java.lang.String value)
    {
        if ((__ZDRIVER_PHONE == null) != (value == null) || (value != null && ! value.equals(__ZDRIVER_PHONE)))
        {
            _isDirty = true;
        }
        __ZDRIVER_PHONE = value;
    }       
    /**
     * get the value of ZVEHICLE_NUMB  
     */
    public java.lang.String getZVEHICLE_NUMB()
    {
        
        return __ZVEHICLE_NUMB;
    }
    
    /**
     * Set the value of ZVEHICLE_NUMB  
     */
    public void setZVEHICLE_NUMB(java.lang.String value)
    {
        if ((__ZVEHICLE_NUMB == null) != (value == null) || (value != null && ! value.equals(__ZVEHICLE_NUMB)))
        {
            _isDirty = true;
        }
        __ZVEHICLE_NUMB = value;
    }       
    /**
     * get the value of IV_VEHICLE_NUMB  
     */
    public java.lang.String getIV_VEHICLE_NUMB()
    {
        
        return __IV_VEHICLE_NUMB;
    }
    
    /**
     * Set the value of IV_VEHICLE_NUMB  
     */
    public void setIV_VEHICLE_NUMB(java.lang.String value)
    {
        if ((__IV_VEHICLE_NUMB == null) != (value == null) || (value != null && ! value.equals(__IV_VEHICLE_NUMB)))
        {
            _isDirty = true;
        }
        __IV_VEHICLE_NUMB = value;
    }       
    /**
     * get the value of IV_BEGDA  
     */
    public java.sql.Date getIV_BEGDA()
    {
        
        return __IV_BEGDA;
    }
    
    /**
     * Set the value of IV_BEGDA  
     */
    public void setIV_BEGDA(java.sql.Date value)
    {
        if ((__IV_BEGDA == null) != (value == null) || (value != null && ! value.equals(__IV_BEGDA)))
        {
            _isDirty = true;
        }
        __IV_BEGDA = value;
    }       
    /**
     * Get the value of operDayRelations  
     */
    public com.sybase.collections.GenericList<ru.terralink.mvideo.sap.Relations> getOperDayRelations()
    {
        return getOperDayRelations(false,false);
    }
    /**
     * Sybase internal use only.
     */
    public com.sybase.collections.GenericList<ru.terralink.mvideo.sap.Relations> getOperDayRelations(boolean ignoreNonPending,boolean ignoreDisableSubmit)
    {
        if (__operDayRelations == null)
        {
            __operDayRelations = ru.terralink.mvideo.sap.Relations.getOperDayRelations_for_OperDay(new java.lang.Long(getSurrogateKey()));
        }
        return (com.sybase.collections.GenericList<ru.terralink.mvideo.sap.Relations>)filterChildren(__operDayRelations, ignoreNonPending, ignoreDisableSubmit, new com.sybase.collections.GenericList<ru.terralink.mvideo.sap.Relations>());
    }
    /**
     * Set the value of operDayRelations  
     */
    public void setOperDayRelations(com.sybase.collections.GenericList<ru.terralink.mvideo.sap.Relations> x)
    {
        __operDayRelations = x;
    }
    /**
     * return operDayRelations filtering by query objects  
     */
    public com.sybase.collections.GenericList<ru.terralink.mvideo.sap.Relations> getOperDayRelationsFilterBy(com.sybase.persistence.Query query)
    {
        return ru.terralink.mvideo.sap.Relations.findWithQuery(initChildrenQuery(query, new String[]{"operDayFK"}));
    }
    
    /**
     * return MBO count filter by query object  
     */
    public int getOperDayRelationsSize(com.sybase.persistence.Query query)
    {
        return ru.terralink.mvideo.sap.Relations.getSize(initChildrenQuery(query, new String[]{"operDayFK"}));
    }       
    /**
     * get the value of cvpOperation  
     */
    public com.sybase.persistence.BigString getCvpOperation()
    {
        
        if(__cvpOperation==null)
        {
        	__cvpOperation = new com.sybase.persistence.internal.BigStringImpl(this, "cvpOperation");
        }
        return __cvpOperation;
    }       
    /**
     * get the value of cvpOperationLobs  
     */
    public com.sybase.persistence.BigString getCvpOperationLobs()
    {
        
        if(__cvpOperationLobs==null)
        {
        	__cvpOperationLobs = new com.sybase.persistence.internal.BigStringImpl(this, "cvpOperationLobs");
        }
        return __cvpOperationLobs;
    }       
    /**
     * get the value of surrogateKey  
     */
    public long getSurrogateKey()
    {
        
        return __surrogateKey;
    }
    
    /**
     * Set the value of surrogateKey  
     */
    public void setSurrogateKey(long value)
    {
        if(__surrogateKey != value)
        {
            _isDirty = true;
        }
        __surrogateKey = value;
    }       
    /**
     * get the value of cvpOperationLength  
     */
    public long getCvpOperationLength()
    {
        
        return __cvpOperationLength;
    }
    
    /**
     * Set the value of cvpOperationLength  
     */
    public void setCvpOperationLength(long value)
    {
        if(__cvpOperationLength != value)
        {
            _isDirty = true;
        }
        __cvpOperationLength = value;
    }       
    /**
     * get the value of cvpOperationLobsLength  
     */
    public long getCvpOperationLobsLength()
    {
        
        return __cvpOperationLobsLength;
    }
    
    /**
     * Set the value of cvpOperationLobsLength  
     */
    public void setCvpOperationLobsLength(long value)
    {
        if(__cvpOperationLobsLength != value)
        {
            _isDirty = true;
        }
        __cvpOperationLobsLength = value;
    }       
    
    private java.util.List filterChildren(java.util.List childrenList, boolean ignoreNonPending, boolean ignoreDisableSubmit, java.util.List filteredList)
    {
        if(ignoreNonPending || ignoreDisableSubmit)
        {
            java.util.Iterator<Object> it = childrenList.iterator();
            while (it.hasNext())
            {
                final Object __o = (Object)(it.next());
                com.sybase.persistence.AbstractEntity __e = (com.sybase.persistence.AbstractEntity)__o;
                boolean __addObj = true;
                if (ignoreNonPending && !__e.isPending())
                {
                    __addObj = false;
                }
                else if (ignoreDisableSubmit && __e.getDisableSubmit())
                {
                    __addObj = false;
                }
                if(__addObj)
                {
                    filteredList.add(__e);
                }
            }
            return filteredList;
        }
        else
        {
            return childrenList;
        }
    }
    
    /**
     * Search mobile business object using surrogateKey
     * @param id surrogateKey
     * @return mobile business object
     */
    public static ru.terralink.mvideo.sap.OperDay find(long id)
    {
        String intervalName = null;
        if(com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.isEnabled)
        {
            intervalName = "OperDay.find()";
            com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.getInstance().startInterval(intervalName, com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.PersistenceRead);
        }
        try
        {
            Object[] keys = new Object[]{id};
            return (ru.terralink.mvideo.sap.OperDay)(DELEGATE.findEntityWithKeys(keys));
        }
        finally
        {
            if(com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.isEnabled)
            {
                com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.getInstance().stopInterval(intervalName);
            }
        }
    }
    
    /**
     * Get the mobile business object by surrogate key.
     * @param id surrogate key
     * @return the mobile business object for the surroget key
     * @exception ObjectNotFoundException Thrown if unable to retrieve mobile business object.
     */
    public static ru.terralink.mvideo.sap.OperDay load(long id)
    {
        return (ru.terralink.mvideo.sap.OperDay)(DELEGATE.load(id));
    }
    
    /**
     * Get surroget key of the mobile business object  
     */
    public java.lang.Long _pk()
    {
        return (java.lang.Long)i_pk();
    }
    
    /** Begin code region: Finder methods **/
    /**
     * return MBO count filter by query object  
     */
    public static int getSize(com.sybase.persistence.Query query)
    {
        return DELEGATE.getSize(query);
    }
    
    /**
     * Find a List of OperDay
     * @param query The query to be filter.
     * @exception PersistenceException Thrown if unable to retrieve mobile business object.
     */
    public static com.sybase.collections.GenericList<ru.terralink.mvideo.sap.OperDay> findWithQuery(com.sybase.persistence.Query query)
    {
        return (com.sybase.collections.GenericList<ru.terralink.mvideo.sap.OperDay>)(Object)DELEGATE.findWithQuery(query, ru.terralink.mvideo.sap.OperDay.class);
    }
    
    /**
     * Find a List of Ru.terralink.mvideo.sap.OperDay
     * @exception PersistentException Thrown if unable to retrieve mobile business object.
     */
    public static com.sybase.collections.GenericList<ru.terralink.mvideo.sap.OperDay> findAll(int skip, int take)
    {
        String intervalName = null;
        if(com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.isEnabled)
        {
            intervalName = "OperDay.findAll";
            com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.getInstance().startInterval(intervalName, com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.PersistenceRead);
        }
        try
        {
            String _selectSQL = "select " + " x.\"a\",x.\"b\",x.\"c\",x.\"d\",x.\"e\",x.\"f\",x.\"g\",x.\"h\",x.\"i\",x.\"pending\",x.\"_pc\",x.\"_rp\",x.\"_rf\",x.\"j\",x.\"_rc\",x.\"_ds\",x.\"cvpOperation_length\",x.\"cvpOperationLobs_length\" FROM \"mvideo5_1_0_operday\" x where (((x.\"pending\" = 1 or not exists (select x_os.\"j\" from \"mvideo5_1_0_op"
                                                + "erday_os\" x_os where x_os.\"j\" = x.\"j\"))))"; 
            return (com.sybase.collections.GenericList<ru.terralink.mvideo.sap.OperDay>)(Object)DELEGATE.findWithSQL(skip, take, _selectSQL, ru.terralink.mvideo.sap.OperDay.class);
        }
        finally
        {
            if(com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.isEnabled)
            {
                com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.getInstance().stopInterval(intervalName);
            }
        }
    }
    /**
     * Find a list of ru.terralink.mvideo.sap.OperDay  
     */
    public static com.sybase.collections.GenericList<ru.terralink.mvideo.sap.OperDay> findAll()
    {
        return findAll(0, Integer.MAX_VALUE);
    }
    /**
     * Find a List of Ru.terralink.mvideo.sap.OperDay
     * @exception PersistentException Thrown if unable to retrieve mobile business object.
     */
    public static com.sybase.collections.GenericList<ru.terralink.mvideo.sap.OperDay> findByTOR_ID(java.lang.String TOR_ID, int skip, int take)
    {
        String intervalName = null;
        if(com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.isEnabled)
        {
            intervalName = "OperDay.findByTOR_ID";
            com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.getInstance().startInterval(intervalName, com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.PersistenceRead);
        }
        try
        {
    
            
                String _selectSQL = " x.\"a\",x.\"b\",x.\"c\",x.\"d\",x.\"e\",x.\"f\",x.\"g\",x.\"h\",x.\"i\",x.\"pending\",x.\"_pc\",x.\"_rp\",x.\"_rf\",x.\"j\",x.\"_rc\",x.\"_ds\",x.\"cvpOperation_length\",x.\"cvpOperationLobs_length\" FROM \"mvideo5_1_0_operday\" x WHERE (((x.\"pending\" = 1 or not exists (select x_os.\"j\" from \"mvideo5_1_0_op"
                                        + "erday_os\" x_os where x_os.\"j\" = x.\"j\")))) and ( x.\"b\" = ?)";
                _selectSQL = "select " + _selectSQL;
                String[] ids = new String[0];
                com.sybase.reflection.DataType[] dts = new com.sybase.reflection.DataType[]{    
                    com.sybase.reflection.DataType.forName("string"),
                };
                Object[] values = new Object[] { 
                    TOR_ID,
                };
                com.sybase.collections.GenericList<Object> res = DELEGATE.findWithSQL(_selectSQL, dts, values, ids, skip, take, ru.terralink.mvideo.sap.OperDay.class);
                return (com.sybase.collections.GenericList<ru.terralink.mvideo.sap.OperDay>)(Object)res;
        }
        finally
        {
            if(com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.isEnabled)
            {
                com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.getInstance().stopInterval(intervalName);
            }
        }
    }
    /**
     * Find a list of ru.terralink.mvideo.sap.OperDay  
     */
    public static com.sybase.collections.GenericList<ru.terralink.mvideo.sap.OperDay> findByTOR_ID(java.lang.String TOR_ID)
    {
        return findByTOR_ID(TOR_ID, 0, Integer.MAX_VALUE);
    }
    /**
     * Find a List of Ru.terralink.mvideo.sap.OperDay
     * @exception PersistentException Thrown if unable to retrieve mobile business object.
     */
    public static com.sybase.collections.GenericList<ru.terralink.mvideo.sap.OperDay> findByIV_VEHICLE_NUMB(java.lang.String IV_VEHICLE_NUMB, int skip, int take)
    {
        String intervalName = null;
        if(com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.isEnabled)
        {
            intervalName = "OperDay.findByIV_VEHICLE_NUMB";
            com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.getInstance().startInterval(intervalName, com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.PersistenceRead);
        }
        try
        {
    
            
                String _selectSQL = " x.\"a\",x.\"b\",x.\"c\",x.\"d\",x.\"e\",x.\"f\",x.\"g\",x.\"h\",x.\"i\",x.\"pending\",x.\"_pc\",x.\"_rp\",x.\"_rf\",x.\"j\",x.\"_rc\",x.\"_ds\",x.\"cvpOperation_length\",x.\"cvpOperationLobs_length\" FROM \"mvideo5_1_0_operday\" x WHERE (((x.\"pending\" = 1 or not exists (select x_os.\"j\" from \"mvideo5_1_0_op"
                                        + "erday_os\" x_os where x_os.\"j\" = x.\"j\")))) and ( x.\"h\" = ?)";
                _selectSQL = "select " + _selectSQL;
                String[] ids = new String[0];
                com.sybase.reflection.DataType[] dts = new com.sybase.reflection.DataType[]{    
                    com.sybase.reflection.DataType.forName("string"),
                };
                Object[] values = new Object[] { 
                    IV_VEHICLE_NUMB,
                };
                com.sybase.collections.GenericList<Object> res = DELEGATE.findWithSQL(_selectSQL, dts, values, ids, skip, take, ru.terralink.mvideo.sap.OperDay.class);
                return (com.sybase.collections.GenericList<ru.terralink.mvideo.sap.OperDay>)(Object)res;
        }
        finally
        {
            if(com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.isEnabled)
            {
                com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.getInstance().stopInterval(intervalName);
            }
        }
    }
    /**
     * Find a list of ru.terralink.mvideo.sap.OperDay  
     */
    public static com.sybase.collections.GenericList<ru.terralink.mvideo.sap.OperDay> findByIV_VEHICLE_NUMB(java.lang.String IV_VEHICLE_NUMB)
    {
        return findByIV_VEHICLE_NUMB(IV_VEHICLE_NUMB, 0, Integer.MAX_VALUE);
    }
    /**
     * Find a List of Ru.terralink.mvideo.sap.OperDay
     * @exception PersistentException Thrown if unable to retrieve mobile business object.
     */
    public static com.sybase.collections.GenericList<ru.terralink.mvideo.sap.OperDay> findByIV_BEGDA(java.sql.Date IV_BEGDA, int skip, int take)
    {
        String intervalName = null;
        if(com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.isEnabled)
        {
            intervalName = "OperDay.findByIV_BEGDA";
            com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.getInstance().startInterval(intervalName, com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.PersistenceRead);
        }
        try
        {
    
            
                String _selectSQL = " x.\"a\",x.\"b\",x.\"c\",x.\"d\",x.\"e\",x.\"f\",x.\"g\",x.\"h\",x.\"i\",x.\"pending\",x.\"_pc\",x.\"_rp\",x.\"_rf\",x.\"j\",x.\"_rc\",x.\"_ds\",x.\"cvpOperation_length\",x.\"cvpOperationLobs_length\" FROM \"mvideo5_1_0_operday\" x WHERE (((x.\"pending\" = 1 or not exists (select x_os.\"j\" from \"mvideo5_1_0_op"
                                        + "erday_os\" x_os where x_os.\"j\" = x.\"j\")))) and ( x.\"i\" = ?)";
                _selectSQL = "select " + _selectSQL;
                String[] ids = new String[0];
                com.sybase.reflection.DataType[] dts = new com.sybase.reflection.DataType[]{    
                    com.sybase.reflection.DataType.forName("date"),
                };
                Object[] values = new Object[] { 
                    IV_BEGDA,
                };
                com.sybase.collections.GenericList<Object> res = DELEGATE.findWithSQL(_selectSQL, dts, values, ids, skip, take, ru.terralink.mvideo.sap.OperDay.class);
                return (com.sybase.collections.GenericList<ru.terralink.mvideo.sap.OperDay>)(Object)res;
        }
        finally
        {
            if(com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.isEnabled)
            {
                com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.getInstance().stopInterval(intervalName);
            }
        }
    }
    /**
     * Find a list of ru.terralink.mvideo.sap.OperDay  
     */
    public static com.sybase.collections.GenericList<ru.terralink.mvideo.sap.OperDay> findByIV_BEGDA(java.sql.Date IV_BEGDA)
    {
        return findByIV_BEGDA(IV_BEGDA, 0, Integer.MAX_VALUE);
    }
    /**
     * Find a mobile business object Ru.terralink.mvideo.sap.OperDay
     * @exception PersistentException Thrown if unable to retrieve mobile business object.
     */
    public static ru.terralink.mvideo.sap.OperDay findByPrimaryKey(java.lang.String TOR_ID
                                                                   ,java.lang.String IV_VEHICLE_NUMB
                                                                   ,java.sql.Date IV_BEGDA)
    {
        String intervalName = null;
        if(com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.isEnabled)
        {
            intervalName = "OperDay.findByPrimaryKey";
            com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.getInstance().startInterval(intervalName, com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.PersistenceRead);
        }
        try
        {
    
            
                String _selectSQL = "SELECT x.\"a\",x.\"b\",x.\"c\",x.\"d\",x.\"e\",x.\"f\",x.\"g\",x.\"h\",x.\"i\",x.\"pending\",x.\"_pc\",x.\"_rp\",x.\"_rf\",x.\"j\",x.\"_rc\",x.\"_ds\",x.\"cvpOperation_length\",x.\"cvpOperationLobs_length\" FROM \"mvideo5_1_0_operday\" x WHERE (((x.\"pending\" = 1 or not exists (select x_os.\"j\" from \"mvideo5_"
                                        + "1_0_operday_os\" x_os where x_os.\"j\" = x.\"j\")))) and ( x.\"b\" = ? AND x.\"h\" = ? AND x.\"i\" = ?)";
                String[] ids = new String[0];
                com.sybase.reflection.DataType[] dts = new com.sybase.reflection.DataType[]{    
                    com.sybase.reflection.DataType.forName("string"),
                    com.sybase.reflection.DataType.forName("string"),
                    com.sybase.reflection.DataType.forName("date"),
                };
                Object[] values = new Object[] { 
                    TOR_ID,
                    IV_VEHICLE_NUMB,
                    IV_BEGDA,
                };
                Object res = DELEGATE.findWithSQL(_selectSQL, dts, values, ids, ru.terralink.mvideo.sap.OperDay.class);
                return (ru.terralink.mvideo.sap.OperDay)res;
        }
        finally
        {
            if(com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.isEnabled)
            {
                com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.getInstance().stopInterval(intervalName);
            }
        }
    }
    
    /**
     * Find a List of Ru.terralink.mvideo.sap.OperDay
     * @exception PersistentException Thrown if unable to retrieve mobile business object.
     */
    public static com.sybase.collections.GenericList<ru.terralink.mvideo.sap.OperDay> getByIvDateAndIvNumber(java.sql.Date BEGIN_DATA, java.lang.String VEHICLE_NUMBER, int skip, int take)
    {
        String intervalName = null;
        if(com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.isEnabled)
        {
            intervalName = "OperDay.getByIvDateAndIvNumber";
            com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.getInstance().startInterval(intervalName, com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.PersistenceRead);
        }
        try
        {
    
            
                String _selectSQL = " x.\"a\",x.\"b\",x.\"c\",x.\"d\",x.\"e\",x.\"f\",x.\"g\",x.\"h\",x.\"i\",x.\"pending\",x.\"_pc\",x.\"_rp\",x.\"_rf\",x.\"j\",x.\"_rc\",x.\"_ds\",x.\"cvpOperation_length\",x.\"cvpOperationLobs_length\" FROM \"mvideo5_1_0_operday\" x WHERE (((x.\"pending\" = 1 or not exists (select x_os.\"j\" from \"mvideo5_1_0_op"
                                        + "erday_os\" x_os where x_os.\"j\" = x.\"j\")))) and ( x.\"i\" = ? AND x.\"h\" = ?)";
                _selectSQL = "select " + _selectSQL;
                String[] ids = new String[0];
                com.sybase.reflection.DataType[] dts = new com.sybase.reflection.DataType[]{    
                    com.sybase.reflection.DataType.forName("date"),
                    com.sybase.reflection.DataType.forName("string"),
                };
                Object[] values = new Object[] { 
                    BEGIN_DATA,
                    VEHICLE_NUMBER,
                };
                com.sybase.collections.GenericList<Object> res = DELEGATE.findWithSQL(_selectSQL, dts, values, ids, skip, take, ru.terralink.mvideo.sap.OperDay.class);
                return (com.sybase.collections.GenericList<ru.terralink.mvideo.sap.OperDay>)(Object)res;
        }
        finally
        {
            if(com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.isEnabled)
            {
                com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.getInstance().stopInterval(intervalName);
            }
        }
    }
    /**
     * Find a list of ru.terralink.mvideo.sap.OperDay  
     */
    public static com.sybase.collections.GenericList<ru.terralink.mvideo.sap.OperDay> getByIvDateAndIvNumber(java.sql.Date BEGIN_DATA,java.lang.String VEHICLE_NUMBER)
    {
        return getByIvDateAndIvNumber(BEGIN_DATA, VEHICLE_NUMBER, 0, Integer.MAX_VALUE);
    }
    
    /**
     * Returns the MBOs that are updated locally but not submitted.  
     */
    public static com.sybase.collections.GenericList<ru.terralink.mvideo.sap.OperDay> getPendingObjects(int skip, int take)
    {
        return (com.sybase.collections.GenericList<ru.terralink.mvideo.sap.OperDay>)(Object)DELEGATE.getPendingObjects(skip, take);
    }
    
    /**
     * Returns the MBOs that are updated locally but not submmited.  
     */
    public static com.sybase.collections.GenericList<ru.terralink.mvideo.sap.OperDay> getPendingObjects()
    {
        return (com.sybase.collections.GenericList<ru.terralink.mvideo.sap.OperDay>)(Object)DELEGATE.getPendingObjects();
    }
    
    /** End code region: Finder methods **/
    /**
     * Returns the log record list.  
     */
    public com.sybase.collections.GenericList<com.sybase.persistence.LogRecord> getLogRecords()
    {
        return ru.terralink.mvideo.sap.LogRecordImpl.findByEntity("OperDay", keyToString());
    }
    
    
    
    
    
    public void create()
    {
        throw new com.sybase.persistence.NoSuchOperationException(com.sybase.persistence.NoSuchOperationException.NO_SUCH_OPERATION);
    }
    
    public void update()
    {
        throw new com.sybase.persistence.NoSuchOperationException(com.sybase.persistence.NoSuchOperationException.NO_SUCH_OPERATION);
    }      
    
    public void delete()
    {
        throw new com.sybase.persistence.NoSuchOperationException(com.sybase.persistence.NoSuchOperationException.NO_SUCH_OPERATION);
    }      
    
    /**
     * @deprecated  
     */
    public static ru.terralink.mvideo.sap.OperDaySynchronizationParameters getSynchronizationParameters()
    {   
        return (ru.terralink.mvideo.sap.OperDaySynchronizationParameters)((com.sybase.sup.client.persistence.SyncParamEntityDelegate)(ru.terralink.mvideo.sap.Mvideo5DB.getDelegate().getEntityDelegate("OperDaySynchronizationParameters"))).getSynchronizationParameters();
    }
    
    /**
     * Gets all EntitySubscriptions for the mobile entity  
     */
    public static com.sybase.collections.GenericList<ru.terralink.mvideo.sap.OperDaySubscription> getSubscriptions()
    {
        com.sybase.collections.GenericList<ru.terralink.mvideo.sap.OperDaySubscription> result = new com.sybase.collections.GenericList<ru.terralink.mvideo.sap.OperDaySubscription>();
        for (ru.terralink.mvideo.sap.intrnl.OperDay_pull_pq pq : ru.terralink.mvideo.sap.intrnl.OperDay_pull_pq.findAll())    
        {
            ru.terralink.mvideo.sap.OperDaySubscription subscription = new ru.terralink.mvideo.sap.OperDaySubscription();
            subscription.setSp_date(pq.getSp_dateParam());    
            subscription.setSp_numb(pq.getSp_numbParam());    
            result.add(subscription);
        }
        return result;
    }
    
    /**
     * Adds a subcription to this entity.  
     */
    public static void addSubscription(ru.terralink.mvideo.sap.OperDaySubscription subscription)
    {
        String username = ru.terralink.mvideo.sap.Mvideo5DB.getSyncUsername();    
        ru.terralink.mvideo.sap.intrnl.OperDay_pull_pq  pqEntity = ru.terralink.mvideo.sap.intrnl.OperDay_pull_pq.findSub(username, (java.sql.Date)subscription.getSp_date(),(java.lang.String)subscription.getSp_numb());	
    	if (pqEntity == null)
        {
            pqEntity = new ru.terralink.mvideo.sap.intrnl.OperDay_pull_pq();		
            pqEntity.setUsername(username);
            pqEntity.setSp_dateParam((java.sql.Date)subscription.getSp_date());    
            pqEntity.setSp_numbParam((java.lang.String)subscription.getSp_numb());    
          	pqEntity.save();    
        }
    }
    
    /**
     * Removes a subscription from this entity.  
     */
    public static void removeSubscription(ru.terralink.mvideo.sap.OperDaySubscription subscription)
    {
        String username = ru.terralink.mvideo.sap.Mvideo5DB.getSyncUsername();
        ru.terralink.mvideo.sap.intrnl.OperDay_pull_pq  pqEntity = ru.terralink.mvideo.sap.intrnl.OperDay_pull_pq.findSub(username, (java.sql.Date)subscription.getSp_date(),(java.lang.String)subscription.getSp_numb());	
        if (pqEntity != null)
        {
            pqEntity.delete();        
        }
    }
    
    
    
    
    /**
     * Submit pending operations of the mobile business object (ready for sending to server)  
     */
    public static void submitPendingOperations()
    {
        DELEGATE.submitPendingOperations();
    }
    
    /**
     * Cancel all the pending operations (not submitted operation).  
     */
    public static void cancelPendingOperations()
    {
        DELEGATE.cancelPendingOperations();
    }
    
    /**
     * Get the last called operation of the mobile business object  
     */
    public String getLastOperation()
    {
        if (!getCvpOperation().isNull())
        {
            com.sybase.afx.json.JsonObject cvpOperation = (com.sybase.afx.json.JsonObject)(com.sybase.afx.json.JsonReader.parse(__cvpOperation.getValue()));
            return (String)cvpOperation.get("cvp_name");
        }
        if (getPendingChange() == 'C')
        {
        }
        else if (getPendingChange() == 'D')
        {
        }
        else if (getPendingChange() == 'U')
        {
        }
        return null;
    }
    
    public ru.terralink.mvideo.sap.OperDay getDownloadState()
    {
        return (ru.terralink.mvideo.sap.OperDay)i_getDownloadState();
    }
    
    public ru.terralink.mvideo.sap.OperDay getOriginalState()
    {
        return (ru.terralink.mvideo.sap.OperDay)i_getOriginalState();
    }
    
    /**
     * Install a callback handler
     */
    public static void registerCallbackHandler(com.sybase.persistence.CallbackHandler handler)
    {
        DELEGATE.registerCallbackHandler(handler);
    }
    
    public static com.sybase.persistence.CallbackHandler getCallbackHandler()
    {
        return DELEGATE.getCallbackHandler();
    }
}