/**
 * Generated by Sybase AFX Compiler with templateJ
 * Compiler version - 2.3.0.183
 * mbs - false 
 */
package ru.terralink.mvideo.sap;

@SuppressWarnings("all")
public  class OperDaySynchronizationParameters extends com.sybase.sup.client.persistence.AbstractSynchronizationParameters implements com.sybase.persistence.LocalBusinessObject, com.sybase.reflection.ClassWithMetaData
{
    /** Begin code region: MetaData **/
    private static ru.terralink.mvideo.sap.intrnl.OperDaySynchronizationParametersMetaData META_DATA = new ru.terralink.mvideo.sap.intrnl.OperDaySynchronizationParametersMetaData();
    
    /**
     * return MetaData object  
     */
    public com.sybase.reflection.ClassMetaData getClassMetaData()
    {
        return META_DATA;
    }
    
    /**
     * return MetaData object  
     */
    public static com.sybase.reflection.EntityMetaData getMetaData()
    {
        return META_DATA;
    }
    
    /** End code region: MetaData **/
    protected static com.sybase.sup.client.persistence.SyncParamEntityDelegate DELEGATE = 
        com.sybase.sup.client.persistence.DelegateFactory.createSyncParamEntityDelegate("OperDaySynchronizationParameters", ru.terralink.mvideo.sap.OperDaySynchronizationParameters.class, META_DATA, ru.terralink.mvideo.sap.Mvideo5DB.getDelegate());
    
    
    /** Begin code region: Properties **/
    private java.sql.Date __sp_date ;
    
    private boolean __sp_dateUserDefined ;
    
    private java.lang.String __sp_numb ;
    
    private boolean __sp_numbUserDefined ;
    
    public java.lang.String getAttributeNullableString(int id)
    {
        switch(id)
        {
        case 513:
            return getSp_numb();
        default:
            return super.getAttributeNullableString(id);
        }
    }
    
    public void setAttributeNullableString(int id, java.lang.String v)
    {
        switch(id)
        {
        case 513:
            setSp_numb((java.lang.String)v);
            break;
        default:
            super.setAttributeNullableString(id, v);
            break;
        }
    }
    public java.lang.String getAttributeString(int id)
    {
        switch(id)
        {
        case 515:
            return getUser_sp();
        default:
            return super.getAttributeString(id);
        }
    }
    
    public void setAttributeString(int id, java.lang.String v)
    {
        switch(id)
        {
        case 515:
            setUser_sp((java.lang.String)v);
            break;
        default:
            super.setAttributeString(id, v);
            break;
        }
    }
    public java.sql.Date getAttributeNullableDate(int id)
    {
        switch(id)
        {
        case 511:
            return getSp_date();
        default:
            return super.getAttributeNullableDate(id);
        }
    }
    
    public void setAttributeNullableDate(int id, java.sql.Date v)
    {
        switch(id)
        {
        case 511:
            setSp_date((java.sql.Date)v);
            break;
        default:
            super.setAttributeNullableDate(id, v);
            break;
        }
    }
    public int getAttributeInt(int id)
    {
        switch(id)
        {
        case 516:
            return getSize_sp();
        default:
            return super.getAttributeInt(id);
        }
    }
    
    public void setAttributeInt(int id, int v)
    {
        switch(id)
        {
        case 516:
            setSize_sp((int)v);
            break;
        default:
            super.setAttributeInt(id, v);
            break;
        }
    }
    public boolean getAttributeBoolean(int id)
    {
        switch(id)
        {
        case 512:
            return getSp_dateUserDefined();
        case 514:
            return getSp_numbUserDefined();
        default:
            return super.getAttributeBoolean(id);
        }
    }
    
    public void setAttributeBoolean(int id, boolean v)
    {
        switch(id)
        {
        case 512:
            setSp_dateUserDefined((boolean)v);
            break;
        case 514:
            setSp_numbUserDefined((boolean)v);
            break;
        default:
            super.setAttributeBoolean(id, v);
            break;
        }
    }
    
    public Object getAttributeJson(int id)
    {
        switch(id)
        {
        default:
            return super.getAttributeJson(id);
        }
    }
    
    public void setAttributeJson(int id, Object value)
    {
        switch(id)
        {
        default:
            super.setAttributeJson(id, value);
            break;
        }
    }
    /** End code region: Properties **/
    
    /** Begin code region: Constructor and init **/
    /**
     * Creates an instance of ru.terralink.mvideo.sap.OperDaySynchronizationParameters  
     */
    public OperDaySynchronizationParameters()
    {
        setEntityDelegate(DELEGATE);
        persistentQueryDelegate = ru.terralink.mvideo.sap.intrnl.OperDay_pull_pq.getEntityDelegateForPQ();
        _init();
    }
    protected void _init()
    {
        
    }
    /** End code region: Constructor and init **/
    
    /**
     * get the value of sp_date  
     */
    public java.sql.Date getSp_date()
    {
        
        return __sp_date;
    }
    
    /**
     * Set the value of sp_date  
     */
    public void setSp_date(java.sql.Date value)
    {
        if ((__sp_date == null) != (value == null) || (value != null && ! value.equals(__sp_date)))
        {
            _isDirty = true;
        }
        if ( __sp_dateUserDefined == false )
        {
            __sp_dateUserDefined = true;
            _isDirty = true;
        }
        __sp_date = value;
        if ( __sp_dateUserDefined == false )
        {
            __sp_dateUserDefined = true;
        }
    }
    /**
     * get the value of sp_dateUserDefined  
     */
    public boolean getSp_dateUserDefined()
    {
        
        return __sp_dateUserDefined;
    }
    
    /**
     * Set the value of sp_dateUserDefined  
     */
    private void setSp_dateUserDefined(boolean value)
    {
        if(__sp_dateUserDefined != value)
        {
            _isDirty = true;
        }
        __sp_dateUserDefined = value;
    }
    /**
     * get the value of sp_numb  
     */
    public java.lang.String getSp_numb()
    {
        
        return __sp_numb;
    }
    
    /**
     * Set the value of sp_numb  
     */
    public void setSp_numb(java.lang.String value)
    {
        if ((__sp_numb == null) != (value == null) || (value != null && ! value.equals(__sp_numb)))
        {
            _isDirty = true;
        }
        if ( __sp_numbUserDefined == false )
        {
            __sp_numbUserDefined = true;
            _isDirty = true;
        }
        __sp_numb = value;
        if ( __sp_numbUserDefined == false )
        {
            __sp_numbUserDefined = true;
        }
    }
    /**
     * get the value of sp_numbUserDefined  
     */
    public boolean getSp_numbUserDefined()
    {
        
        return __sp_numbUserDefined;
    }
    
    /**
     * Set the value of sp_numbUserDefined  
     */
    private void setSp_numbUserDefined(boolean value)
    {
        if(__sp_numbUserDefined != value)
        {
            _isDirty = true;
        }
        __sp_numbUserDefined = value;
    }
    
    /**
     * Search mobile business object using surrogateKey
     * @param id surrogateKey
     * @return mobile business object
     */
    public static ru.terralink.mvideo.sap.OperDaySynchronizationParameters find(java.lang.String id)
    {
        String intervalName = null;
        if(com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.isEnabled)
        {
            intervalName = "OperDaySynchronizationParameters.find()";
            com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.getInstance().startInterval(intervalName, com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.PersistenceRead);
        }
        try
        {
            Object[] keys = new Object[]{id};
            return (ru.terralink.mvideo.sap.OperDaySynchronizationParameters)(DELEGATE.findEntityWithKeys(keys));
        }
        finally
        {
            if(com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.isEnabled)
            {
                com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.getInstance().stopInterval(intervalName);
            }
        }
    }
    
    /**
     * Get the mobile business object by surrogate key.
     * @param id surrogate key
     * @return the mobile business object for the surroget key
     * @exception ObjectNotFoundException Thrown if unable to retrieve mobile business object.
     */
    public static ru.terralink.mvideo.sap.OperDaySynchronizationParameters load(java.lang.String id)
    {
        return (ru.terralink.mvideo.sap.OperDaySynchronizationParameters)(DELEGATE.load(id));
    }
    
    /**
     * Get surroget key of the mobile business object  
     */
    public java.lang.String _pk()
    {
        return (java.lang.String)i_pk();
    }
    
    /** Begin code region: Finder methods **/
    
    
    
    /** End code region: Finder methods **/
}