/**
 * Generated by Sybase AFX Compiler with templateJ
 * Compiler version - 2.3.0.183
 * mbs - false 
 */
package ru.terralink.mvideo.sap;

@SuppressWarnings("all")
public  class Orders extends com.sybase.persistence.AbstractEntity implements com.sybase.persistence.MobileBusinessObject, com.sybase.reflection.ClassWithMetaData
{
    /** Begin code region: MetaData **/
    private static ru.terralink.mvideo.sap.intrnl.OrdersMetaData META_DATA = new ru.terralink.mvideo.sap.intrnl.OrdersMetaData();
    
    /**
     * return MetaData object  
     */
    public com.sybase.reflection.ClassMetaData getClassMetaData()
    {
        return META_DATA;
    }
    
    /**
     * return MetaData object  
     */
    public static com.sybase.reflection.EntityMetaData getMetaData()
    {
        return META_DATA;
    }
    
    /** End code region: MetaData **/
    protected static com.sybase.sup.client.persistence.EntityDelegate DELEGATE = 
        com.sybase.sup.client.persistence.DelegateFactory.createEntityDelegate("Orders", ru.terralink.mvideo.sap.Orders.class, "mvideo5.Orders", META_DATA, ru.terralink.mvideo.sap.Mvideo5DB.getDelegate());
    
    
    /** Begin code region: Properties **/
    private java.lang.String __EVENT_CODE ;  
    
    private java.lang.String __TOR_ID ;  
    
    private java.sql.Date __REQ_START_DATE ;  
    
    private java.sql.Time __REQ_START_TIME ;  
    
    private java.sql.Date __REQ_END_DATE ;  
    
    private java.sql.Time __REQ_END_TIME ;  
    
    private double __XPOS ;  
    
    private double __YPOS ;  
    
    private java.lang.String __EXECUTION ;  
    
    private java.lang.String __DDTEXT ;  
    
    private java.lang.String __NAME1 ;  
    
    private java.lang.String __NAME2 ;  
    
    private java.lang.String __NAME3 ;  
    
    private java.lang.String __NAME4 ;  
    
    private java.lang.String __TEL_NUMBER ;  
    
    private java.lang.String __ZTEL_NUMBER2 ;  
    
    private java.lang.String __SMTP_ADDR ;  
    
    private java.lang.String __REGION ;  
    
    private java.lang.String __CITY1 ;  
    
    private java.lang.String __POST_CODE1 ;  
    
    private java.lang.String __STREET ;  
    
    private java.lang.String __HOUSE_NUM1 ;  
    
    private java.lang.String __HOUSE_NUM2 ;  
    
    private java.lang.String __BUILDING ;  
    
    private java.lang.String __FLOOR ;  
    
    private java.lang.String __ROOMNUMBER ;  
    
    private java.lang.String __ZCOMMENTS ;  
    
    private java.lang.String __ZSALES_OBJECT ;  
    
    private java.lang.String __ZEXT_NUM1 ;  
    
    private java.lang.String __ZEXT_NUM2 ;  
    
    private java.lang.String __LOCNO ;  
    
    private java.sql.Date __DEPARTURE_FROM_LOC_DATE ;  
    
    private java.sql.Time __DEPARTURE_FROM_LOC_TIME ;  
    
    private java.sql.Date __ARRIVAL_AT_LOC_DATE ;  
    
    private java.sql.Time __ARRIVAL_AT_LOC_TIME ;  
    
    private java.lang.String __IV_FO_TOR_ID ;  
    
    private java.lang.String __IV_FU_TOR_ID ;  
    
    private ru.terralink.mvideo.sap.Relations __relations ;  
    
    private com.sybase.collections.GenericList<ru.terralink.mvideo.sap.Products> __ordersProductss ;  
    
      
    
      
    
      
    
      
    
    private com.sybase.persistence.BigString __cvpOperation ;  
    
    private com.sybase.persistence.BigString __cvpOperationLobs ;  
    
    private java.lang.Long __relationsFK ;  
    
    private boolean __relationsValid ;  
    
    private long __surrogateKey ;  
    
      
    
      
    
    private long __cvpOperationLength ;  
    
    private long __cvpOperationLobsLength ;  
    
    public double getAttributeDouble(int id)
    {
        switch(id)
        {
        case 114:
            return getXPOS();
        case 115:
            return getYPOS();
        default:
            return super.getAttributeDouble(id);
        }
    }
    
    public void setAttributeDouble(int id, double v)
    {
        switch(id)
        {
        case 114:
            setXPOS((double)v);
            break;
        case 115:
            setYPOS((double)v);
            break;
        default:
            super.setAttributeDouble(id, v);
            break;
        }
    }
    public long getAttributeLong(int id)
    {
        switch(id)
        {
        case 145:
            return getSurrogateKey();
        case 1277:
            return getCvpOperationLength();
        case 1278:
            return getCvpOperationLobsLength();
        default:
            return super.getAttributeLong(id);
        }
    }
    
    public void setAttributeLong(int id, long v)
    {
        switch(id)
        {
        case 145:
            setSurrogateKey((long)v);
            break;
        case 1277:
            setCvpOperationLength((long)v);
            break;
        case 1278:
            setCvpOperationLobsLength((long)v);
            break;
        default:
            super.setAttributeLong(id, v);
            break;
        }
    }
    public com.sybase.persistence.BigString getAttributeNullableBigString(int id)
    {
        switch(id)
        {
        case 718:
            return getCvpOperation();
        case 719:
            return getCvpOperationLobs();
        default:
            return super.getAttributeNullableBigString(id);
        }
    }
    
    public java.lang.String getAttributeString(int id)
    {
        switch(id)
        {
        case 108:
            return getEVENT_CODE();
        case 109:
            return getTOR_ID();
        case 116:
            return getEXECUTION();
        case 117:
            return getDDTEXT();
        case 118:
            return getNAME1();
        case 119:
            return getNAME2();
        case 120:
            return getNAME3();
        case 121:
            return getNAME4();
        case 122:
            return getTEL_NUMBER();
        case 123:
            return getZTEL_NUMBER2();
        case 124:
            return getSMTP_ADDR();
        case 125:
            return getREGION();
        case 126:
            return getCITY1();
        case 127:
            return getPOST_CODE1();
        case 128:
            return getSTREET();
        case 129:
            return getHOUSE_NUM1();
        case 130:
            return getHOUSE_NUM2();
        case 131:
            return getBUILDING();
        case 132:
            return getFLOOR();
        case 133:
            return getROOMNUMBER();
        case 134:
            return getZCOMMENTS();
        case 135:
            return getZSALES_OBJECT();
        case 136:
            return getZEXT_NUM1();
        case 137:
            return getZEXT_NUM2();
        case 138:
            return getLOCNO();
        case 143:
            return getIV_FO_TOR_ID();
        case 144:
            return getIV_FU_TOR_ID();
        default:
            return super.getAttributeString(id);
        }
    }
    
    public void setAttributeString(int id, java.lang.String v)
    {
        switch(id)
        {
        case 108:
            setEVENT_CODE((java.lang.String)v);
            break;
        case 109:
            setTOR_ID((java.lang.String)v);
            break;
        case 116:
            setEXECUTION((java.lang.String)v);
            break;
        case 117:
            setDDTEXT((java.lang.String)v);
            break;
        case 118:
            setNAME1((java.lang.String)v);
            break;
        case 119:
            setNAME2((java.lang.String)v);
            break;
        case 120:
            setNAME3((java.lang.String)v);
            break;
        case 121:
            setNAME4((java.lang.String)v);
            break;
        case 122:
            setTEL_NUMBER((java.lang.String)v);
            break;
        case 123:
            setZTEL_NUMBER2((java.lang.String)v);
            break;
        case 124:
            setSMTP_ADDR((java.lang.String)v);
            break;
        case 125:
            setREGION((java.lang.String)v);
            break;
        case 126:
            setCITY1((java.lang.String)v);
            break;
        case 127:
            setPOST_CODE1((java.lang.String)v);
            break;
        case 128:
            setSTREET((java.lang.String)v);
            break;
        case 129:
            setHOUSE_NUM1((java.lang.String)v);
            break;
        case 130:
            setHOUSE_NUM2((java.lang.String)v);
            break;
        case 131:
            setBUILDING((java.lang.String)v);
            break;
        case 132:
            setFLOOR((java.lang.String)v);
            break;
        case 133:
            setROOMNUMBER((java.lang.String)v);
            break;
        case 134:
            setZCOMMENTS((java.lang.String)v);
            break;
        case 135:
            setZSALES_OBJECT((java.lang.String)v);
            break;
        case 136:
            setZEXT_NUM1((java.lang.String)v);
            break;
        case 137:
            setZEXT_NUM2((java.lang.String)v);
            break;
        case 138:
            setLOCNO((java.lang.String)v);
            break;
        case 143:
            setIV_FO_TOR_ID((java.lang.String)v);
            break;
        case 144:
            setIV_FU_TOR_ID((java.lang.String)v);
            break;
        default:
            super.setAttributeString(id, v);
            break;
        }
    }
    public java.lang.Long getAttributeNullableLong(int id)
    {
        switch(id)
        {
        case 792:
            return getRelationsFK();
        default:
            return super.getAttributeNullableLong(id);
        }
    }
    
    public void setAttributeNullableLong(int id, java.lang.Long v)
    {
        switch(id)
        {
        case 792:
            setRelationsFK((java.lang.Long)v);
            break;
        default:
            super.setAttributeNullableLong(id, v);
            break;
        }
    }
    public java.sql.Time getAttributeNullableTime(int id)
    {
        switch(id)
        {
        case 111:
            return getREQ_START_TIME();
        case 113:
            return getREQ_END_TIME();
        case 140:
            return getDEPARTURE_FROM_LOC_TIME();
        case 142:
            return getARRIVAL_AT_LOC_TIME();
        default:
            return super.getAttributeNullableTime(id);
        }
    }
    
    public void setAttributeNullableTime(int id, java.sql.Time v)
    {
        switch(id)
        {
        case 111:
            setREQ_START_TIME((java.sql.Time)v);
            break;
        case 113:
            setREQ_END_TIME((java.sql.Time)v);
            break;
        case 140:
            setDEPARTURE_FROM_LOC_TIME((java.sql.Time)v);
            break;
        case 142:
            setARRIVAL_AT_LOC_TIME((java.sql.Time)v);
            break;
        default:
            super.setAttributeNullableTime(id, v);
            break;
        }
    }
    public java.sql.Date getAttributeNullableDate(int id)
    {
        switch(id)
        {
        case 110:
            return getREQ_START_DATE();
        case 112:
            return getREQ_END_DATE();
        case 139:
            return getDEPARTURE_FROM_LOC_DATE();
        case 141:
            return getARRIVAL_AT_LOC_DATE();
        default:
            return super.getAttributeNullableDate(id);
        }
    }
    
    public void setAttributeNullableDate(int id, java.sql.Date v)
    {
        switch(id)
        {
        case 110:
            setREQ_START_DATE((java.sql.Date)v);
            break;
        case 112:
            setREQ_END_DATE((java.sql.Date)v);
            break;
        case 139:
            setDEPARTURE_FROM_LOC_DATE((java.sql.Date)v);
            break;
        case 141:
            setARRIVAL_AT_LOC_DATE((java.sql.Date)v);
            break;
        default:
            super.setAttributeNullableDate(id, v);
            break;
        }
    }
    public boolean getAttributeBoolean(int id)
    {
        switch(id)
        {
        case 796:
            return getRelationsValid();
        default:
            return super.getAttributeBoolean(id);
        }
    }
    
    public void setAttributeBoolean(int id, boolean v)
    {
        switch(id)
        {
        case 796:
            setRelationsValid((boolean)v);
            break;
        default:
            super.setAttributeBoolean(id, v);
            break;
        }
    }
    public java.lang.Object getAttributeObject(int id, boolean loadFromDBIfInvalid)
    {
        switch(id)
        {
        case 146:
            if(loadFromDBIfInvalid)
            {
                return getRelations();
            }
            else
            {
                return __relations;
            }
        case 147:
            if(loadFromDBIfInvalid)
            {
                return getOrdersProductss();
            }
            else
            {
                return __ordersProductss;
            }
        default:
            return super.getAttributeObject(id);
        }
    }
    
    public void setAttributeObject(int id, java.lang.Object v)
    {
        switch(id)
        {
        case 146:
            setRelations((ru.terralink.mvideo.sap.Relations)v);
            break;
        case 147:
            setOrdersProductss((com.sybase.collections.GenericList<ru.terralink.mvideo.sap.Products>)v);
            break;
        default:
            super.setAttributeObject(id, v);
            break;
        }
    }
    
    public Object getAttributeJson(int id)
    {
        switch(id)
        {
        default:
            return super.getAttributeJson(id);
        }
    }
    
    public void setAttributeJson(int id, Object value)
    {
        switch(id)
        {
        default:
            super.setAttributeJson(id, value);
            break;
        }
    }
    /** End code region: Properties **/
    
    /** Begin code region: Constructor and init **/
    /**
     * Creates an instance of ru.terralink.mvideo.sap.Orders  
     */
    public Orders()
    {
        setEntityDelegate(DELEGATE);
        _init();
    }
    protected void _init()
    {
        
    }
    /** End code region: Constructor and init **/
    
    /**
     * get the value of EVENT_CODE  
     */
    public java.lang.String getEVENT_CODE()
    {
        
        return __EVENT_CODE;
    }
    
    /**
     * Set the value of EVENT_CODE  
     */
    public void setEVENT_CODE(java.lang.String value)
    {
        if ((__EVENT_CODE == null) != (value == null) || (value != null && ! value.equals(__EVENT_CODE)))
        {
            _isDirty = true;
        }
        __EVENT_CODE = value;
    }       
    /**
     * get the value of TOR_ID  
     */
    public java.lang.String getTOR_ID()
    {
        
        return __TOR_ID;
    }
    
    /**
     * Set the value of TOR_ID  
     */
    public void setTOR_ID(java.lang.String value)
    {
        if ((__TOR_ID == null) != (value == null) || (value != null && ! value.equals(__TOR_ID)))
        {
            _isDirty = true;
        }
        __TOR_ID = value;
    }       
    /**
     * get the value of REQ_START_DATE  
     */
    public java.sql.Date getREQ_START_DATE()
    {
        
        return __REQ_START_DATE;
    }
    
    /**
     * Set the value of REQ_START_DATE  
     */
    public void setREQ_START_DATE(java.sql.Date value)
    {
        if ((__REQ_START_DATE == null) != (value == null) || (value != null && ! value.equals(__REQ_START_DATE)))
        {
            _isDirty = true;
        }
        __REQ_START_DATE = value;
    }       
    /**
     * get the value of REQ_START_TIME  
     */
    public java.sql.Time getREQ_START_TIME()
    {
        
        return __REQ_START_TIME;
    }
    
    /**
     * Set the value of REQ_START_TIME  
     */
    public void setREQ_START_TIME(java.sql.Time value)
    {
        if ((__REQ_START_TIME == null) != (value == null) || (value != null && ! value.equals(__REQ_START_TIME)))
        {
            _isDirty = true;
        }
        __REQ_START_TIME = value;
    }       
    /**
     * get the value of REQ_END_DATE  
     */
    public java.sql.Date getREQ_END_DATE()
    {
        
        return __REQ_END_DATE;
    }
    
    /**
     * Set the value of REQ_END_DATE  
     */
    public void setREQ_END_DATE(java.sql.Date value)
    {
        if ((__REQ_END_DATE == null) != (value == null) || (value != null && ! value.equals(__REQ_END_DATE)))
        {
            _isDirty = true;
        }
        __REQ_END_DATE = value;
    }       
    /**
     * get the value of REQ_END_TIME  
     */
    public java.sql.Time getREQ_END_TIME()
    {
        
        return __REQ_END_TIME;
    }
    
    /**
     * Set the value of REQ_END_TIME  
     */
    public void setREQ_END_TIME(java.sql.Time value)
    {
        if ((__REQ_END_TIME == null) != (value == null) || (value != null && ! value.equals(__REQ_END_TIME)))
        {
            _isDirty = true;
        }
        __REQ_END_TIME = value;
    }       
    /**
     * get the value of XPOS  
     */
    public double getXPOS()
    {
        
        return __XPOS;
    }
    
    /**
     * Set the value of XPOS  
     */
    public void setXPOS(double value)
    {
        if(__XPOS != value)
        {
            _isDirty = true;
        }
        __XPOS = value;
    }       
    /**
     * get the value of YPOS  
     */
    public double getYPOS()
    {
        
        return __YPOS;
    }
    
    /**
     * Set the value of YPOS  
     */
    public void setYPOS(double value)
    {
        if(__YPOS != value)
        {
            _isDirty = true;
        }
        __YPOS = value;
    }       
    /**
     * get the value of EXECUTION  
     */
    public java.lang.String getEXECUTION()
    {
        
        return __EXECUTION;
    }
    
    /**
     * Set the value of EXECUTION  
     */
    public void setEXECUTION(java.lang.String value)
    {
        if ((__EXECUTION == null) != (value == null) || (value != null && ! value.equals(__EXECUTION)))
        {
            _isDirty = true;
        }
        __EXECUTION = value;
    }       
    /**
     * get the value of DDTEXT  
     */
    public java.lang.String getDDTEXT()
    {
        
        return __DDTEXT;
    }
    
    /**
     * Set the value of DDTEXT  
     */
    public void setDDTEXT(java.lang.String value)
    {
        if ((__DDTEXT == null) != (value == null) || (value != null && ! value.equals(__DDTEXT)))
        {
            _isDirty = true;
        }
        __DDTEXT = value;
    }       
    /**
     * get the value of NAME1  
     */
    public java.lang.String getNAME1()
    {
        
        return __NAME1;
    }
    
    /**
     * Set the value of NAME1  
     */
    public void setNAME1(java.lang.String value)
    {
        if ((__NAME1 == null) != (value == null) || (value != null && ! value.equals(__NAME1)))
        {
            _isDirty = true;
        }
        __NAME1 = value;
    }       
    /**
     * get the value of NAME2  
     */
    public java.lang.String getNAME2()
    {
        
        return __NAME2;
    }
    
    /**
     * Set the value of NAME2  
     */
    public void setNAME2(java.lang.String value)
    {
        if ((__NAME2 == null) != (value == null) || (value != null && ! value.equals(__NAME2)))
        {
            _isDirty = true;
        }
        __NAME2 = value;
    }       
    /**
     * get the value of NAME3  
     */
    public java.lang.String getNAME3()
    {
        
        return __NAME3;
    }
    
    /**
     * Set the value of NAME3  
     */
    public void setNAME3(java.lang.String value)
    {
        if ((__NAME3 == null) != (value == null) || (value != null && ! value.equals(__NAME3)))
        {
            _isDirty = true;
        }
        __NAME3 = value;
    }       
    /**
     * get the value of NAME4  
     */
    public java.lang.String getNAME4()
    {
        
        return __NAME4;
    }
    
    /**
     * Set the value of NAME4  
     */
    public void setNAME4(java.lang.String value)
    {
        if ((__NAME4 == null) != (value == null) || (value != null && ! value.equals(__NAME4)))
        {
            _isDirty = true;
        }
        __NAME4 = value;
    }       
    /**
     * get the value of TEL_NUMBER  
     */
    public java.lang.String getTEL_NUMBER()
    {
        
        return __TEL_NUMBER;
    }
    
    /**
     * Set the value of TEL_NUMBER  
     */
    public void setTEL_NUMBER(java.lang.String value)
    {
        if ((__TEL_NUMBER == null) != (value == null) || (value != null && ! value.equals(__TEL_NUMBER)))
        {
            _isDirty = true;
        }
        __TEL_NUMBER = value;
    }       
    /**
     * get the value of ZTEL_NUMBER2  
     */
    public java.lang.String getZTEL_NUMBER2()
    {
        
        return __ZTEL_NUMBER2;
    }
    
    /**
     * Set the value of ZTEL_NUMBER2  
     */
    public void setZTEL_NUMBER2(java.lang.String value)
    {
        if ((__ZTEL_NUMBER2 == null) != (value == null) || (value != null && ! value.equals(__ZTEL_NUMBER2)))
        {
            _isDirty = true;
        }
        __ZTEL_NUMBER2 = value;
    }       
    /**
     * get the value of SMTP_ADDR  
     */
    public java.lang.String getSMTP_ADDR()
    {
        
        return __SMTP_ADDR;
    }
    
    /**
     * Set the value of SMTP_ADDR  
     */
    public void setSMTP_ADDR(java.lang.String value)
    {
        if ((__SMTP_ADDR == null) != (value == null) || (value != null && ! value.equals(__SMTP_ADDR)))
        {
            _isDirty = true;
        }
        __SMTP_ADDR = value;
    }       
    /**
     * get the value of REGION  
     */
    public java.lang.String getREGION()
    {
        
        return __REGION;
    }
    
    /**
     * Set the value of REGION  
     */
    public void setREGION(java.lang.String value)
    {
        if ((__REGION == null) != (value == null) || (value != null && ! value.equals(__REGION)))
        {
            _isDirty = true;
        }
        __REGION = value;
    }       
    /**
     * get the value of CITY1  
     */
    public java.lang.String getCITY1()
    {
        
        return __CITY1;
    }
    
    /**
     * Set the value of CITY1  
     */
    public void setCITY1(java.lang.String value)
    {
        if ((__CITY1 == null) != (value == null) || (value != null && ! value.equals(__CITY1)))
        {
            _isDirty = true;
        }
        __CITY1 = value;
    }       
    /**
     * get the value of POST_CODE1  
     */
    public java.lang.String getPOST_CODE1()
    {
        
        return __POST_CODE1;
    }
    
    /**
     * Set the value of POST_CODE1  
     */
    public void setPOST_CODE1(java.lang.String value)
    {
        if ((__POST_CODE1 == null) != (value == null) || (value != null && ! value.equals(__POST_CODE1)))
        {
            _isDirty = true;
        }
        __POST_CODE1 = value;
    }       
    /**
     * get the value of STREET  
     */
    public java.lang.String getSTREET()
    {
        
        return __STREET;
    }
    
    /**
     * Set the value of STREET  
     */
    public void setSTREET(java.lang.String value)
    {
        if ((__STREET == null) != (value == null) || (value != null && ! value.equals(__STREET)))
        {
            _isDirty = true;
        }
        __STREET = value;
    }       
    /**
     * get the value of HOUSE_NUM1  
     */
    public java.lang.String getHOUSE_NUM1()
    {
        
        return __HOUSE_NUM1;
    }
    
    /**
     * Set the value of HOUSE_NUM1  
     */
    public void setHOUSE_NUM1(java.lang.String value)
    {
        if ((__HOUSE_NUM1 == null) != (value == null) || (value != null && ! value.equals(__HOUSE_NUM1)))
        {
            _isDirty = true;
        }
        __HOUSE_NUM1 = value;
    }       
    /**
     * get the value of HOUSE_NUM2  
     */
    public java.lang.String getHOUSE_NUM2()
    {
        
        return __HOUSE_NUM2;
    }
    
    /**
     * Set the value of HOUSE_NUM2  
     */
    public void setHOUSE_NUM2(java.lang.String value)
    {
        if ((__HOUSE_NUM2 == null) != (value == null) || (value != null && ! value.equals(__HOUSE_NUM2)))
        {
            _isDirty = true;
        }
        __HOUSE_NUM2 = value;
    }       
    /**
     * get the value of BUILDING  
     */
    public java.lang.String getBUILDING()
    {
        
        return __BUILDING;
    }
    
    /**
     * Set the value of BUILDING  
     */
    public void setBUILDING(java.lang.String value)
    {
        if ((__BUILDING == null) != (value == null) || (value != null && ! value.equals(__BUILDING)))
        {
            _isDirty = true;
        }
        __BUILDING = value;
    }       
    /**
     * get the value of FLOOR  
     */
    public java.lang.String getFLOOR()
    {
        
        return __FLOOR;
    }
    
    /**
     * Set the value of FLOOR  
     */
    public void setFLOOR(java.lang.String value)
    {
        if ((__FLOOR == null) != (value == null) || (value != null && ! value.equals(__FLOOR)))
        {
            _isDirty = true;
        }
        __FLOOR = value;
    }       
    /**
     * get the value of ROOMNUMBER  
     */
    public java.lang.String getROOMNUMBER()
    {
        
        return __ROOMNUMBER;
    }
    
    /**
     * Set the value of ROOMNUMBER  
     */
    public void setROOMNUMBER(java.lang.String value)
    {
        if ((__ROOMNUMBER == null) != (value == null) || (value != null && ! value.equals(__ROOMNUMBER)))
        {
            _isDirty = true;
        }
        __ROOMNUMBER = value;
    }       
    /**
     * get the value of ZCOMMENTS  
     */
    public java.lang.String getZCOMMENTS()
    {
        
        return __ZCOMMENTS;
    }
    
    /**
     * Set the value of ZCOMMENTS  
     */
    public void setZCOMMENTS(java.lang.String value)
    {
        if ((__ZCOMMENTS == null) != (value == null) || (value != null && ! value.equals(__ZCOMMENTS)))
        {
            _isDirty = true;
        }
        __ZCOMMENTS = value;
    }       
    /**
     * get the value of ZSALES_OBJECT  
     */
    public java.lang.String getZSALES_OBJECT()
    {
        
        return __ZSALES_OBJECT;
    }
    
    /**
     * Set the value of ZSALES_OBJECT  
     */
    public void setZSALES_OBJECT(java.lang.String value)
    {
        if ((__ZSALES_OBJECT == null) != (value == null) || (value != null && ! value.equals(__ZSALES_OBJECT)))
        {
            _isDirty = true;
        }
        __ZSALES_OBJECT = value;
    }       
    /**
     * get the value of ZEXT_NUM1  
     */
    public java.lang.String getZEXT_NUM1()
    {
        
        return __ZEXT_NUM1;
    }
    
    /**
     * Set the value of ZEXT_NUM1  
     */
    public void setZEXT_NUM1(java.lang.String value)
    {
        if ((__ZEXT_NUM1 == null) != (value == null) || (value != null && ! value.equals(__ZEXT_NUM1)))
        {
            _isDirty = true;
        }
        __ZEXT_NUM1 = value;
    }       
    /**
     * get the value of ZEXT_NUM2  
     */
    public java.lang.String getZEXT_NUM2()
    {
        
        return __ZEXT_NUM2;
    }
    
    /**
     * Set the value of ZEXT_NUM2  
     */
    public void setZEXT_NUM2(java.lang.String value)
    {
        if ((__ZEXT_NUM2 == null) != (value == null) || (value != null && ! value.equals(__ZEXT_NUM2)))
        {
            _isDirty = true;
        }
        __ZEXT_NUM2 = value;
    }       
    /**
     * get the value of LOCNO  
     */
    public java.lang.String getLOCNO()
    {
        
        return __LOCNO;
    }
    
    /**
     * Set the value of LOCNO  
     */
    public void setLOCNO(java.lang.String value)
    {
        if ((__LOCNO == null) != (value == null) || (value != null && ! value.equals(__LOCNO)))
        {
            _isDirty = true;
        }
        __LOCNO = value;
    }       
    /**
     * get the value of DEPARTURE_FROM_LOC_DATE  
     */
    public java.sql.Date getDEPARTURE_FROM_LOC_DATE()
    {
        
        return __DEPARTURE_FROM_LOC_DATE;
    }
    
    /**
     * Set the value of DEPARTURE_FROM_LOC_DATE  
     */
    public void setDEPARTURE_FROM_LOC_DATE(java.sql.Date value)
    {
        if ((__DEPARTURE_FROM_LOC_DATE == null) != (value == null) || (value != null && ! value.equals(__DEPARTURE_FROM_LOC_DATE)))
        {
            _isDirty = true;
        }
        __DEPARTURE_FROM_LOC_DATE = value;
    }       
    /**
     * get the value of DEPARTURE_FROM_LOC_TIME  
     */
    public java.sql.Time getDEPARTURE_FROM_LOC_TIME()
    {
        
        return __DEPARTURE_FROM_LOC_TIME;
    }
    
    /**
     * Set the value of DEPARTURE_FROM_LOC_TIME  
     */
    public void setDEPARTURE_FROM_LOC_TIME(java.sql.Time value)
    {
        if ((__DEPARTURE_FROM_LOC_TIME == null) != (value == null) || (value != null && ! value.equals(__DEPARTURE_FROM_LOC_TIME)))
        {
            _isDirty = true;
        }
        __DEPARTURE_FROM_LOC_TIME = value;
    }       
    /**
     * get the value of ARRIVAL_AT_LOC_DATE  
     */
    public java.sql.Date getARRIVAL_AT_LOC_DATE()
    {
        
        return __ARRIVAL_AT_LOC_DATE;
    }
    
    /**
     * Set the value of ARRIVAL_AT_LOC_DATE  
     */
    public void setARRIVAL_AT_LOC_DATE(java.sql.Date value)
    {
        if ((__ARRIVAL_AT_LOC_DATE == null) != (value == null) || (value != null && ! value.equals(__ARRIVAL_AT_LOC_DATE)))
        {
            _isDirty = true;
        }
        __ARRIVAL_AT_LOC_DATE = value;
    }       
    /**
     * get the value of ARRIVAL_AT_LOC_TIME  
     */
    public java.sql.Time getARRIVAL_AT_LOC_TIME()
    {
        
        return __ARRIVAL_AT_LOC_TIME;
    }
    
    /**
     * Set the value of ARRIVAL_AT_LOC_TIME  
     */
    public void setARRIVAL_AT_LOC_TIME(java.sql.Time value)
    {
        if ((__ARRIVAL_AT_LOC_TIME == null) != (value == null) || (value != null && ! value.equals(__ARRIVAL_AT_LOC_TIME)))
        {
            _isDirty = true;
        }
        __ARRIVAL_AT_LOC_TIME = value;
    }       
    /**
     * get the value of IV_FO_TOR_ID  
     */
    public java.lang.String getIV_FO_TOR_ID()
    {
        
        return __IV_FO_TOR_ID;
    }
    
    /**
     * Set the value of IV_FO_TOR_ID  
     */
    public void setIV_FO_TOR_ID(java.lang.String value)
    {
        if ((__IV_FO_TOR_ID == null) != (value == null) || (value != null && ! value.equals(__IV_FO_TOR_ID)))
        {
            _isDirty = true;
        }
        __IV_FO_TOR_ID = value;
    }       
    /**
     * get the value of IV_FU_TOR_ID  
     */
    public java.lang.String getIV_FU_TOR_ID()
    {
        
        return __IV_FU_TOR_ID;
    }
    
    /**
     * Set the value of IV_FU_TOR_ID  
     */
    public void setIV_FU_TOR_ID(java.lang.String value)
    {
        if ((__IV_FU_TOR_ID == null) != (value == null) || (value != null && ! value.equals(__IV_FU_TOR_ID)))
        {
            _isDirty = true;
        }
        __IV_FU_TOR_ID = value;
    }       
    /**
     * get the value of relations  
     */
    public ru.terralink.mvideo.sap.Relations getRelations()
    {
        if (! __relationsValid)
        {
            if( (__relationsFK != null))
            {
                __relations = ru.terralink.mvideo.sap.Relations.find(__relationsFK);
            }
            __relationsValid = true;
        }
        return __relations;
    }
    
    /**
     * Set the value of relations  
     */
    public void setRelations(ru.terralink.mvideo.sap.Relations value)
    {
        if (getRelations() != null)
        {
            if( !__relations.equals(value) )
            {
                _isDirty = true;
            }
        }
        else if(value != null)
        {
            _isDirty = true;
        }
        if(__relations != null)
        {
            __relations.setDirty(_isDirty);
        }
        if (value == null)
        {
            __relationsFK = null;
        }
        else
        {
            value.setDirty(_isDirty);
            __relationsFK = value._pk();
            __IV_FO_TOR_ID = value.getFO_TOR_ID();
            __IV_FU_TOR_ID = value.getFU_TOR_ID();
        }
        __relationsValid = true;
        __relations = value;
    }       
    /**
     * Get the value of ordersProductss  
     */
    public com.sybase.collections.GenericList<ru.terralink.mvideo.sap.Products> getOrdersProductss()
    {
        return getOrdersProductss(false,false);
    }
    /**
     * Sybase internal use only.
     */
    public com.sybase.collections.GenericList<ru.terralink.mvideo.sap.Products> getOrdersProductss(boolean ignoreNonPending,boolean ignoreDisableSubmit)
    {
        if (__ordersProductss == null)
        {
            __ordersProductss = ru.terralink.mvideo.sap.Products.getOrdersProductss_for_Orders(new java.lang.Long(getSurrogateKey()));
        }
        return (com.sybase.collections.GenericList<ru.terralink.mvideo.sap.Products>)filterChildren(__ordersProductss, ignoreNonPending, ignoreDisableSubmit, new com.sybase.collections.GenericList<ru.terralink.mvideo.sap.Products>());
    }
    /**
     * Set the value of ordersProductss  
     */
    public void setOrdersProductss(com.sybase.collections.GenericList<ru.terralink.mvideo.sap.Products> x)
    {
        __ordersProductss = x;
    }
    /**
     * return ordersProductss filtering by query objects  
     */
    public com.sybase.collections.GenericList<ru.terralink.mvideo.sap.Products> getOrdersProductssFilterBy(com.sybase.persistence.Query query)
    {
        return ru.terralink.mvideo.sap.Products.findWithQuery(initChildrenQuery(query, new String[]{"ordersFK"}));
    }
    
    /**
     * return MBO count filter by query object  
     */
    public int getOrdersProductssSize(com.sybase.persistence.Query query)
    {
        return ru.terralink.mvideo.sap.Products.getSize(initChildrenQuery(query, new String[]{"ordersFK"}));
    }       
    /**
     * get the value of cvpOperation  
     */
    public com.sybase.persistence.BigString getCvpOperation()
    {
        
        if(__cvpOperation==null)
        {
        	__cvpOperation = new com.sybase.persistence.internal.BigStringImpl(this, "cvpOperation");
        }
        return __cvpOperation;
    }       
    /**
     * get the value of cvpOperationLobs  
     */
    public com.sybase.persistence.BigString getCvpOperationLobs()
    {
        
        if(__cvpOperationLobs==null)
        {
        	__cvpOperationLobs = new com.sybase.persistence.internal.BigStringImpl(this, "cvpOperationLobs");
        }
        return __cvpOperationLobs;
    }       
    /**
     * get the value of relationsFK  
     */
    public java.lang.Long getRelationsFK()
    {
        
        return __relationsFK;
    }
    
    /**
     * Set the value of relationsFK  
     */
    public void setRelationsFK(java.lang.Long value)
    {
        if ((__relationsFK == null) != (value == null) || (value != null && ! value.equals(__relationsFK)))
        {
            __relationsValid = false;
            _isDirty = true;
        }
        __relationsFK = value;
    }       
    /**
     * get the value of relationsValid  
     */
    private boolean getRelationsValid()
    {
        
        return __relationsValid;
    }
    
    /**
     * Set the value of relationsValid  
     */
    private void setRelationsValid(boolean value)
    {
        __relationsValid = value;
    }       
    /**
     * get the value of surrogateKey  
     */
    public long getSurrogateKey()
    {
        
        return __surrogateKey;
    }
    
    /**
     * Set the value of surrogateKey  
     */
    public void setSurrogateKey(long value)
    {
        if(__surrogateKey != value)
        {
            _isDirty = true;
        }
        __surrogateKey = value;
    }       
    /**
     * get the value of cvpOperationLength  
     */
    public long getCvpOperationLength()
    {
        
        return __cvpOperationLength;
    }
    
    /**
     * Set the value of cvpOperationLength  
     */
    public void setCvpOperationLength(long value)
    {
        if(__cvpOperationLength != value)
        {
            _isDirty = true;
        }
        __cvpOperationLength = value;
    }       
    /**
     * get the value of cvpOperationLobsLength  
     */
    public long getCvpOperationLobsLength()
    {
        
        return __cvpOperationLobsLength;
    }
    
    /**
     * Set the value of cvpOperationLobsLength  
     */
    public void setCvpOperationLobsLength(long value)
    {
        if(__cvpOperationLobsLength != value)
        {
            _isDirty = true;
        }
        __cvpOperationLobsLength = value;
    }       
    
    private java.util.List filterChildren(java.util.List childrenList, boolean ignoreNonPending, boolean ignoreDisableSubmit, java.util.List filteredList)
    {
        if(ignoreNonPending || ignoreDisableSubmit)
        {
            java.util.Iterator<Object> it = childrenList.iterator();
            while (it.hasNext())
            {
                final Object __o = (Object)(it.next());
                com.sybase.persistence.AbstractEntity __e = (com.sybase.persistence.AbstractEntity)__o;
                boolean __addObj = true;
                if (ignoreNonPending && !__e.isPending())
                {
                    __addObj = false;
                }
                else if (ignoreDisableSubmit && __e.getDisableSubmit())
                {
                    __addObj = false;
                }
                if(__addObj)
                {
                    filteredList.add(__e);
                }
            }
            return filteredList;
        }
        else
        {
            return childrenList;
        }
    }
    
    /**
     * Search mobile business object using surrogateKey
     * @param id surrogateKey
     * @return mobile business object
     */
    public static ru.terralink.mvideo.sap.Orders find(long id)
    {
        String intervalName = null;
        if(com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.isEnabled)
        {
            intervalName = "Orders.find()";
            com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.getInstance().startInterval(intervalName, com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.PersistenceRead);
        }
        try
        {
            Object[] keys = new Object[]{id};
            return (ru.terralink.mvideo.sap.Orders)(DELEGATE.findEntityWithKeys(keys));
        }
        finally
        {
            if(com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.isEnabled)
            {
                com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.getInstance().stopInterval(intervalName);
            }
        }
    }
    
    /**
     * Get the mobile business object by surrogate key.
     * @param id surrogate key
     * @return the mobile business object for the surroget key
     * @exception ObjectNotFoundException Thrown if unable to retrieve mobile business object.
     */
    public static ru.terralink.mvideo.sap.Orders load(long id)
    {
        return (ru.terralink.mvideo.sap.Orders)(DELEGATE.load(id));
    }
    
    /**
     * Get surroget key of the mobile business object  
     */
    public java.lang.Long _pk()
    {
        return (java.lang.Long)i_pk();
    }
    
    /** Begin code region: Finder methods **/
    /**
     * return MBO count filter by query object  
     */
    public static int getSize(com.sybase.persistence.Query query)
    {
        return DELEGATE.getSize(query);
    }
    
    /**
     * Find a List of Orders
     * @param query The query to be filter.
     * @exception PersistenceException Thrown if unable to retrieve mobile business object.
     */
    public static com.sybase.collections.GenericList<ru.terralink.mvideo.sap.Orders> findWithQuery(com.sybase.persistence.Query query)
    {
        return (com.sybase.collections.GenericList<ru.terralink.mvideo.sap.Orders>)(Object)DELEGATE.findWithQuery(query, ru.terralink.mvideo.sap.Orders.class);
    }
    
    /**
     * Find a List of Ru.terralink.mvideo.sap.Orders
     * @exception PersistentException Thrown if unable to retrieve mobile business object.
     */
    public static com.sybase.collections.GenericList<ru.terralink.mvideo.sap.Orders> findAll(int skip, int take)
    {
        String intervalName = null;
        if(com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.isEnabled)
        {
            intervalName = "Orders.findAll";
            com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.getInstance().startInterval(intervalName, com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.PersistenceRead);
        }
        try
        {
            String _selectSQL = "select " + " x.\"a\",x.\"b\",x.\"c\",x.\"d\",x.\"e\",x.\"f\",x.\"g\",x.\"h\",x.\"i\",x.\"j\",x.\"l\",x.\"m\",x.\"n\",x.\"o\",x.\"p\",x.\"q\",x.\"r\",x.\"s\",x.\"t\",x.\"u\",x.\"v\",x.\"w\",x.\"x\",x.\"y\",x.\"z\",x.\"ba\",x.\"bb\",x.\"bc\",x.\"bd\",x.\"be\",x.\"bf\",x.\"bg\",x.\"bh\",x.\"bi\",x.\"bj\",x.\"bl\",x.\"bm\",x.\"pending\",x.\"_pc\",x.\"_rp\",x.\"_rf\""
                                                + ",x.\"relationsFK\",x.\"bn\",x.\"_rc\",x.\"_ds\",x.\"cvpOperation_length\",x.\"cvpOperationLobs_length\" FROM \"mvideo5_1_0_orders\" x where (((x.\"pending\" = 1 or not exists (select x_os.\"bn\" from \"mvideo5_1_0_orders_os\" x_os where x_os.\"bn\" = x.\"bn\"))))"; 
            return (com.sybase.collections.GenericList<ru.terralink.mvideo.sap.Orders>)(Object)DELEGATE.findWithSQL(skip, take, _selectSQL, ru.terralink.mvideo.sap.Orders.class);
        }
        finally
        {
            if(com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.isEnabled)
            {
                com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.getInstance().stopInterval(intervalName);
            }
        }
    }
    /**
     * Find a list of ru.terralink.mvideo.sap.Orders  
     */
    public static com.sybase.collections.GenericList<ru.terralink.mvideo.sap.Orders> findAll()
    {
        return findAll(0, Integer.MAX_VALUE);
    }
    /**
     * Find a List of Ru.terralink.mvideo.sap.Orders
     * @exception PersistentException Thrown if unable to retrieve mobile business object.
     */
    public static com.sybase.collections.GenericList<ru.terralink.mvideo.sap.Orders> findByIV_FO_TOR_ID(java.lang.String IV_FO_TOR_ID, int skip, int take)
    {
        String intervalName = null;
        if(com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.isEnabled)
        {
            intervalName = "Orders.findByIV_FO_TOR_ID";
            com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.getInstance().startInterval(intervalName, com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.PersistenceRead);
        }
        try
        {
    
            
                String _selectSQL = " x.\"a\",x.\"b\",x.\"c\",x.\"d\",x.\"e\",x.\"f\",x.\"g\",x.\"h\",x.\"i\",x.\"j\",x.\"l\",x.\"m\",x.\"n\",x.\"o\",x.\"p\",x.\"q\",x.\"r\",x.\"s\",x.\"t\",x.\"u\",x.\"v\",x.\"w\",x.\"x\",x.\"y\",x.\"z\",x.\"ba\",x.\"bb\",x.\"bc\",x.\"bd\",x.\"be\",x.\"bf\",x.\"bg\",x.\"bh\",x.\"bi\",x.\"bj\",x.\"bl\",x.\"bm\",x.\"pending\",x.\"_pc\",x.\"_rp\",x.\"_rf\""
                                        + ",x.\"relationsFK\",x.\"bn\",x.\"_rc\",x.\"_ds\",x.\"cvpOperation_length\",x.\"cvpOperationLobs_length\" FROM \"mvideo5_1_0_orders\" x WHERE (((x.\"pending\" = 1 or not exists (select x_os.\"bn\" from \"mvideo5_1_0_orders_os\" x_os where x_os.\"bn\" = x.\"bn\")))) and ( x.\"bl\" = ?)";
                _selectSQL = "select " + _selectSQL;
                String[] ids = new String[0];
                com.sybase.reflection.DataType[] dts = new com.sybase.reflection.DataType[]{    
                    com.sybase.reflection.DataType.forName("string"),
                };
                Object[] values = new Object[] { 
                    IV_FO_TOR_ID,
                };
                com.sybase.collections.GenericList<Object> res = DELEGATE.findWithSQL(_selectSQL, dts, values, ids, skip, take, ru.terralink.mvideo.sap.Orders.class);
                return (com.sybase.collections.GenericList<ru.terralink.mvideo.sap.Orders>)(Object)res;
        }
        finally
        {
            if(com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.isEnabled)
            {
                com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.getInstance().stopInterval(intervalName);
            }
        }
    }
    /**
     * Find a list of ru.terralink.mvideo.sap.Orders  
     */
    public static com.sybase.collections.GenericList<ru.terralink.mvideo.sap.Orders> findByIV_FO_TOR_ID(java.lang.String IV_FO_TOR_ID)
    {
        return findByIV_FO_TOR_ID(IV_FO_TOR_ID, 0, Integer.MAX_VALUE);
    }
    /**
     * Find a List of Ru.terralink.mvideo.sap.Orders
     * @exception PersistentException Thrown if unable to retrieve mobile business object.
     */
    public static com.sybase.collections.GenericList<ru.terralink.mvideo.sap.Orders> findByIV_FU_TOR_ID(java.lang.String IV_FU_TOR_ID, int skip, int take)
    {
        String intervalName = null;
        if(com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.isEnabled)
        {
            intervalName = "Orders.findByIV_FU_TOR_ID";
            com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.getInstance().startInterval(intervalName, com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.PersistenceRead);
        }
        try
        {
    
            
                String _selectSQL = " x.\"a\",x.\"b\",x.\"c\",x.\"d\",x.\"e\",x.\"f\",x.\"g\",x.\"h\",x.\"i\",x.\"j\",x.\"l\",x.\"m\",x.\"n\",x.\"o\",x.\"p\",x.\"q\",x.\"r\",x.\"s\",x.\"t\",x.\"u\",x.\"v\",x.\"w\",x.\"x\",x.\"y\",x.\"z\",x.\"ba\",x.\"bb\",x.\"bc\",x.\"bd\",x.\"be\",x.\"bf\",x.\"bg\",x.\"bh\",x.\"bi\",x.\"bj\",x.\"bl\",x.\"bm\",x.\"pending\",x.\"_pc\",x.\"_rp\",x.\"_rf\""
                                        + ",x.\"relationsFK\",x.\"bn\",x.\"_rc\",x.\"_ds\",x.\"cvpOperation_length\",x.\"cvpOperationLobs_length\" FROM \"mvideo5_1_0_orders\" x WHERE (((x.\"pending\" = 1 or not exists (select x_os.\"bn\" from \"mvideo5_1_0_orders_os\" x_os where x_os.\"bn\" = x.\"bn\")))) and ( x.\"bm\" = ?)";
                _selectSQL = "select " + _selectSQL;
                String[] ids = new String[0];
                com.sybase.reflection.DataType[] dts = new com.sybase.reflection.DataType[]{    
                    com.sybase.reflection.DataType.forName("string"),
                };
                Object[] values = new Object[] { 
                    IV_FU_TOR_ID,
                };
                com.sybase.collections.GenericList<Object> res = DELEGATE.findWithSQL(_selectSQL, dts, values, ids, skip, take, ru.terralink.mvideo.sap.Orders.class);
                return (com.sybase.collections.GenericList<ru.terralink.mvideo.sap.Orders>)(Object)res;
        }
        finally
        {
            if(com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.isEnabled)
            {
                com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.getInstance().stopInterval(intervalName);
            }
        }
    }
    /**
     * Find a list of ru.terralink.mvideo.sap.Orders  
     */
    public static com.sybase.collections.GenericList<ru.terralink.mvideo.sap.Orders> findByIV_FU_TOR_ID(java.lang.String IV_FU_TOR_ID)
    {
        return findByIV_FU_TOR_ID(IV_FU_TOR_ID, 0, Integer.MAX_VALUE);
    }
    /**
     * Find a mobile business object Ru.terralink.mvideo.sap.Orders
     * @exception PersistentException Thrown if unable to retrieve mobile business object.
     */
    public static ru.terralink.mvideo.sap.Orders findByPrimaryKey(java.lang.String IV_FO_TOR_ID
                                                                  ,java.lang.String IV_FU_TOR_ID)
    {
        String intervalName = null;
        if(com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.isEnabled)
        {
            intervalName = "Orders.findByPrimaryKey";
            com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.getInstance().startInterval(intervalName, com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.PersistenceRead);
        }
        try
        {
    
            
                String _selectSQL = "SELECT x.\"a\",x.\"b\",x.\"c\",x.\"d\",x.\"e\",x.\"f\",x.\"g\",x.\"h\",x.\"i\",x.\"j\",x.\"l\",x.\"m\",x.\"n\",x.\"o\",x.\"p\",x.\"q\",x.\"r\",x.\"s\",x.\"t\",x.\"u\",x.\"v\",x.\"w\",x.\"x\",x.\"y\",x.\"z\",x.\"ba\",x.\"bb\",x.\"bc\",x.\"bd\",x.\"be\",x.\"bf\",x.\"bg\",x.\"bh\",x.\"bi\",x.\"bj\",x.\"bl\",x.\"bm\",x.\"pending\",x.\"_pc\",x.\"_rp\",x"
                                        + ".\"_rf\",x.\"relationsFK\",x.\"bn\",x.\"_rc\",x.\"_ds\",x.\"cvpOperation_length\",x.\"cvpOperationLobs_length\" FROM \"mvideo5_1_0_orders\" x WHERE (((x.\"pending\" = 1 or not exists (select x_os.\"bn\" from \"mvideo5_1_0_orders_os\" x_os where x_os.\"bn\" = x.\"bn\")))) and ( x.\"bl\" = ? AND x.\"bm\" = ?)";
                String[] ids = new String[0];
                com.sybase.reflection.DataType[] dts = new com.sybase.reflection.DataType[]{    
                    com.sybase.reflection.DataType.forName("string"),
                    com.sybase.reflection.DataType.forName("string"),
                };
                Object[] values = new Object[] { 
                    IV_FO_TOR_ID,
                    IV_FU_TOR_ID,
                };
                Object res = DELEGATE.findWithSQL(_selectSQL, dts, values, ids, ru.terralink.mvideo.sap.Orders.class);
                return (ru.terralink.mvideo.sap.Orders)res;
        }
        finally
        {
            if(com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.isEnabled)
            {
                com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.getInstance().stopInterval(intervalName);
            }
        }
    }
    
    /**
     * Find a List of Ru.terralink.mvideo.sap.Orders
     * @exception PersistentException Thrown if unable to retrieve mobile business object.
     */
    public static com.sybase.collections.GenericList<ru.terralink.mvideo.sap.Orders> getRelationsOrderss_for_Relations(java.lang.Long surrogateKey, int skip, int take)
    {
        String intervalName = null;
        if(com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.isEnabled)
        {
            intervalName = "Orders.getRelationsOrderss_for_Relations";
            com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.getInstance().startInterval(intervalName, com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.PersistenceRead);
        }
        try
        {
    
            
                String _selectSQL = " x.\"a\",x.\"b\",x.\"c\",x.\"d\",x.\"e\",x.\"f\",x.\"g\",x.\"h\",x.\"i\",x.\"j\",x.\"l\",x.\"m\",x.\"n\",x.\"o\",x.\"p\",x.\"q\",x.\"r\",x.\"s\",x.\"t\",x.\"u\",x.\"v\",x.\"w\",x.\"x\",x.\"y\",x.\"z\",x.\"ba\",x.\"bb\",x.\"bc\",x.\"bd\",x.\"be\",x.\"bf\",x.\"bg\",x.\"bh\",x.\"bi\",x.\"bj\",x.\"bl\",x.\"bm\",x.\"pending\",x.\"_pc\",x.\"_rp\",x.\"_rf\""
                                        + ",x.\"relationsFK\",x.\"bn\",x.\"_rc\",x.\"_ds\",x.\"cvpOperation_length\",x.\"cvpOperationLobs_length\" from \"mvideo5_1_0_orders\" x where (((x.\"pending\" = 1 or not exists (select x_os.\"bn\" from \"mvideo5_1_0_orders_os\" x_os where x_os.\"bn\" = x.\"bn\")))) and ( x.\"relationsFK\"=?)";
                _selectSQL = "select " + _selectSQL;
                String[] ids = new String[0];
                com.sybase.reflection.DataType[] dts = new com.sybase.reflection.DataType[]{    
                    com.sybase.reflection.DataType.forName("long?"),
                };
                Object[] values = new Object[] { 
                    surrogateKey,
                };
                com.sybase.collections.GenericList<Object> res = DELEGATE.findWithSQL(_selectSQL, dts, values, ids, skip, take, ru.terralink.mvideo.sap.Orders.class);
                return (com.sybase.collections.GenericList<ru.terralink.mvideo.sap.Orders>)(Object)res;
        }
        finally
        {
            if(com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.isEnabled)
            {
                com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.getInstance().stopInterval(intervalName);
            }
        }
    }
    /**
     * Find a list of ru.terralink.mvideo.sap.Orders  
     */
    public static com.sybase.collections.GenericList<ru.terralink.mvideo.sap.Orders> getRelationsOrderss_for_Relations(java.lang.Long surrogateKey)
    {
        return getRelationsOrderss_for_Relations(surrogateKey, 0, Integer.MAX_VALUE);
    }
    
    /**
     * Returns the MBOs that are updated locally but not submitted.  
     */
    public static com.sybase.collections.GenericList<ru.terralink.mvideo.sap.Orders> getPendingObjects(int skip, int take)
    {
        return (com.sybase.collections.GenericList<ru.terralink.mvideo.sap.Orders>)(Object)DELEGATE.getPendingObjects(skip, take);
    }
    
    /**
     * Returns the MBOs that are updated locally but not submmited.  
     */
    public static com.sybase.collections.GenericList<ru.terralink.mvideo.sap.Orders> getPendingObjects()
    {
        return (com.sybase.collections.GenericList<ru.terralink.mvideo.sap.Orders>)(Object)DELEGATE.getPendingObjects();
    }
    
    /** End code region: Finder methods **/
    /**
     * Returns the log record list.  
     */
    public com.sybase.collections.GenericList<com.sybase.persistence.LogRecord> getLogRecords()
    {
        return ru.terralink.mvideo.sap.LogRecordImpl.findByEntity("Orders", keyToString());
    }
    
    
    
    
    
    public void create()
    {
        throw new com.sybase.persistence.NoSuchOperationException(com.sybase.persistence.NoSuchOperationException.NO_SUCH_OPERATION);
    }
    
    public void update()
    {
        throw new com.sybase.persistence.NoSuchOperationException(com.sybase.persistence.NoSuchOperationException.NO_SUCH_OPERATION);
    }      
    
    public void delete()
    {
        throw new com.sybase.persistence.NoSuchOperationException(com.sybase.persistence.NoSuchOperationException.NO_SUCH_OPERATION);
    }      
    
    
    
    
    /**
     * Submit pending operations of the mobile business object (ready for sending to server)  
     */
    public static void submitPendingOperations()
    {
        DELEGATE.submitPendingOperations();
    }
    
    /**
     * Cancel all the pending operations (not submitted operation).  
     */
    public static void cancelPendingOperations()
    {
        DELEGATE.cancelPendingOperations();
    }
    
    /**
     * Get the last called operation of the mobile business object  
     */
    public String getLastOperation()
    {
        if (!getCvpOperation().isNull())
        {
            com.sybase.afx.json.JsonObject cvpOperation = (com.sybase.afx.json.JsonObject)(com.sybase.afx.json.JsonReader.parse(__cvpOperation.getValue()));
            return (String)cvpOperation.get("cvp_name");
        }
        if (getPendingChange() == 'C')
        {
        }
        else if (getPendingChange() == 'D')
        {
        }
        else if (getPendingChange() == 'U')
        {
        }
        return null;
    }
    
    public ru.terralink.mvideo.sap.Orders getDownloadState()
    {
        return (ru.terralink.mvideo.sap.Orders)i_getDownloadState();
    }
    
    public ru.terralink.mvideo.sap.Orders getOriginalState()
    {
        return (ru.terralink.mvideo.sap.Orders)i_getOriginalState();
    }
    
    /**
     * Install a callback handler
     */
    public static void registerCallbackHandler(com.sybase.persistence.CallbackHandler handler)
    {
        DELEGATE.registerCallbackHandler(handler);
    }
    
    public static com.sybase.persistence.CallbackHandler getCallbackHandler()
    {
        return DELEGATE.getCallbackHandler();
    }
}