/**
 * Generated by Sybase AFX Compiler with templateJ
 * Compiler version - 2.3.0.183
 * mbs - false 
 */
package ru.terralink.mvideo.sap;

@SuppressWarnings("all")
public  class Products extends com.sybase.persistence.AbstractEntity implements com.sybase.persistence.MobileBusinessObject, com.sybase.reflection.ClassWithMetaData
{
    /** Begin code region: MetaData **/
    private static ru.terralink.mvideo.sap.intrnl.ProductsMetaData META_DATA = new ru.terralink.mvideo.sap.intrnl.ProductsMetaData();
    
    /**
     * return MetaData object  
     */
    public com.sybase.reflection.ClassMetaData getClassMetaData()
    {
        return META_DATA;
    }
    
    /**
     * return MetaData object  
     */
    public static com.sybase.reflection.EntityMetaData getMetaData()
    {
        return META_DATA;
    }
    
    /** End code region: MetaData **/
    protected static com.sybase.sup.client.persistence.EntityDelegate DELEGATE = 
        com.sybase.sup.client.persistence.DelegateFactory.createEntityDelegate("Products", ru.terralink.mvideo.sap.Products.class, "mvideo5.Products", META_DATA, ru.terralink.mvideo.sap.Mvideo5DB.getDelegate());
    
    
    /** Begin code region: Properties **/
    private java.lang.String __TOR_ID ;  
    
    private java.lang.String __ITEM_ID ;  
    
    private java.lang.String __PRODUCT_ID ;  
    
    private java.lang.String __ITEM_DESCR ;  
    
    private java.math.BigDecimal __QUA_PCS_VAL ;  
    
    private java.lang.String __QUA_PCS_UNI ;  
    
    private java.math.BigDecimal __AMT_GDSV_VAL ;  
    
    private java.lang.String __AMT_GDSV_CUR ;  
    
    private java.lang.String __ZADDSERV ;  
    
    private java.lang.String __IV_FU_TOR_ID ;  
    
    private java.lang.String __IV_FO_TOR_ID ;  
    
    private ru.terralink.mvideo.sap.Orders __orders ;  
    
      
    
      
    
      
    
      
    
    private com.sybase.persistence.BigString __cvpOperation ;  
    
    private com.sybase.persistence.BigString __cvpOperationLobs ;  
    
    private java.lang.Long __ordersFK ;  
    
    private boolean __ordersValid ;  
    
    private long __surrogateKey ;  
    
      
    
      
    
    private long __cvpOperationLength ;  
    
    private long __cvpOperationLobsLength ;  
    
    public long getAttributeLong(int id)
    {
        switch(id)
        {
        case 191:
            return getSurrogateKey();
        case 1300:
            return getCvpOperationLength();
        case 1301:
            return getCvpOperationLobsLength();
        default:
            return super.getAttributeLong(id);
        }
    }
    
    public void setAttributeLong(int id, long v)
    {
        switch(id)
        {
        case 191:
            setSurrogateKey((long)v);
            break;
        case 1300:
            setCvpOperationLength((long)v);
            break;
        case 1301:
            setCvpOperationLobsLength((long)v);
            break;
        default:
            super.setAttributeLong(id, v);
            break;
        }
    }
    public com.sybase.persistence.BigString getAttributeNullableBigString(int id)
    {
        switch(id)
        {
        case 817:
            return getCvpOperation();
        case 818:
            return getCvpOperationLobs();
        default:
            return super.getAttributeNullableBigString(id);
        }
    }
    
    public java.math.BigDecimal getAttributeDecimal(int id)
    {
        switch(id)
        {
        case 184:
            return getQUA_PCS_VAL();
        case 186:
            return getAMT_GDSV_VAL();
        default:
            return super.getAttributeDecimal(id);
        }
    }
    
    public void setAttributeDecimal(int id, java.math.BigDecimal v)
    {
        switch(id)
        {
        case 184:
            setQUA_PCS_VAL((java.math.BigDecimal)v);
            break;
        case 186:
            setAMT_GDSV_VAL((java.math.BigDecimal)v);
            break;
        default:
            super.setAttributeDecimal(id, v);
            break;
        }
    }
    public java.lang.String getAttributeString(int id)
    {
        switch(id)
        {
        case 180:
            return getTOR_ID();
        case 181:
            return getITEM_ID();
        case 182:
            return getPRODUCT_ID();
        case 183:
            return getITEM_DESCR();
        case 185:
            return getQUA_PCS_UNI();
        case 187:
            return getAMT_GDSV_CUR();
        case 188:
            return getZADDSERV();
        case 189:
            return getIV_FU_TOR_ID();
        case 190:
            return getIV_FO_TOR_ID();
        default:
            return super.getAttributeString(id);
        }
    }
    
    public void setAttributeString(int id, java.lang.String v)
    {
        switch(id)
        {
        case 180:
            setTOR_ID((java.lang.String)v);
            break;
        case 181:
            setITEM_ID((java.lang.String)v);
            break;
        case 182:
            setPRODUCT_ID((java.lang.String)v);
            break;
        case 183:
            setITEM_DESCR((java.lang.String)v);
            break;
        case 185:
            setQUA_PCS_UNI((java.lang.String)v);
            break;
        case 187:
            setAMT_GDSV_CUR((java.lang.String)v);
            break;
        case 188:
            setZADDSERV((java.lang.String)v);
            break;
        case 189:
            setIV_FU_TOR_ID((java.lang.String)v);
            break;
        case 190:
            setIV_FO_TOR_ID((java.lang.String)v);
            break;
        default:
            super.setAttributeString(id, v);
            break;
        }
    }
    public java.lang.Long getAttributeNullableLong(int id)
    {
        switch(id)
        {
        case 842:
            return getOrdersFK();
        default:
            return super.getAttributeNullableLong(id);
        }
    }
    
    public void setAttributeNullableLong(int id, java.lang.Long v)
    {
        switch(id)
        {
        case 842:
            setOrdersFK((java.lang.Long)v);
            break;
        default:
            super.setAttributeNullableLong(id, v);
            break;
        }
    }
    public boolean getAttributeBoolean(int id)
    {
        switch(id)
        {
        case 846:
            return getOrdersValid();
        default:
            return super.getAttributeBoolean(id);
        }
    }
    
    public void setAttributeBoolean(int id, boolean v)
    {
        switch(id)
        {
        case 846:
            setOrdersValid((boolean)v);
            break;
        default:
            super.setAttributeBoolean(id, v);
            break;
        }
    }
    public java.lang.Object getAttributeObject(int id, boolean loadFromDBIfInvalid)
    {
        switch(id)
        {
        case 192:
            if(loadFromDBIfInvalid)
            {
                return getOrders();
            }
            else
            {
                return __orders;
            }
        default:
            return super.getAttributeObject(id);
        }
    }
    
    public void setAttributeObject(int id, java.lang.Object v)
    {
        switch(id)
        {
        case 192:
            setOrders((ru.terralink.mvideo.sap.Orders)v);
            break;
        default:
            super.setAttributeObject(id, v);
            break;
        }
    }
    
    public Object getAttributeJson(int id)
    {
        switch(id)
        {
        default:
            return super.getAttributeJson(id);
        }
    }
    
    public void setAttributeJson(int id, Object value)
    {
        switch(id)
        {
        default:
            super.setAttributeJson(id, value);
            break;
        }
    }
    /** End code region: Properties **/
    
    /** Begin code region: Constructor and init **/
    /**
     * Creates an instance of ru.terralink.mvideo.sap.Products  
     */
    public Products()
    {
        setEntityDelegate(DELEGATE);
        _init();
    }
    protected void _init()
    {
        
    }
    /** End code region: Constructor and init **/
    
    /**
     * get the value of TOR_ID  
     */
    public java.lang.String getTOR_ID()
    {
        
        return __TOR_ID;
    }
    
    /**
     * Set the value of TOR_ID  
     */
    public void setTOR_ID(java.lang.String value)
    {
        if ((__TOR_ID == null) != (value == null) || (value != null && ! value.equals(__TOR_ID)))
        {
            _isDirty = true;
        }
        __TOR_ID = value;
    }       
    /**
     * get the value of ITEM_ID  
     */
    public java.lang.String getITEM_ID()
    {
        
        return __ITEM_ID;
    }
    
    /**
     * Set the value of ITEM_ID  
     */
    public void setITEM_ID(java.lang.String value)
    {
        if ((__ITEM_ID == null) != (value == null) || (value != null && ! value.equals(__ITEM_ID)))
        {
            _isDirty = true;
        }
        __ITEM_ID = value;
    }       
    /**
     * get the value of PRODUCT_ID  
     */
    public java.lang.String getPRODUCT_ID()
    {
        
        return __PRODUCT_ID;
    }
    
    /**
     * Set the value of PRODUCT_ID  
     */
    public void setPRODUCT_ID(java.lang.String value)
    {
        if ((__PRODUCT_ID == null) != (value == null) || (value != null && ! value.equals(__PRODUCT_ID)))
        {
            _isDirty = true;
        }
        __PRODUCT_ID = value;
    }       
    /**
     * get the value of ITEM_DESCR  
     */
    public java.lang.String getITEM_DESCR()
    {
        
        return __ITEM_DESCR;
    }
    
    /**
     * Set the value of ITEM_DESCR  
     */
    public void setITEM_DESCR(java.lang.String value)
    {
        if ((__ITEM_DESCR == null) != (value == null) || (value != null && ! value.equals(__ITEM_DESCR)))
        {
            _isDirty = true;
        }
        __ITEM_DESCR = value;
    }       
    /**
     * get the value of QUA_PCS_VAL  
     */
    public java.math.BigDecimal getQUA_PCS_VAL()
    {
        
        return __QUA_PCS_VAL;
    }
    
    /**
     * Set the value of QUA_PCS_VAL  
     */
    public void setQUA_PCS_VAL(java.math.BigDecimal value)
    {
        if ((__QUA_PCS_VAL == null) != (value == null) || (value != null && ! value.equals(__QUA_PCS_VAL)))
        {
            _isDirty = true;
        }
        __QUA_PCS_VAL = value;
    }       
    /**
     * get the value of QUA_PCS_UNI  
     */
    public java.lang.String getQUA_PCS_UNI()
    {
        
        return __QUA_PCS_UNI;
    }
    
    /**
     * Set the value of QUA_PCS_UNI  
     */
    public void setQUA_PCS_UNI(java.lang.String value)
    {
        if ((__QUA_PCS_UNI == null) != (value == null) || (value != null && ! value.equals(__QUA_PCS_UNI)))
        {
            _isDirty = true;
        }
        __QUA_PCS_UNI = value;
    }       
    /**
     * get the value of AMT_GDSV_VAL  
     */
    public java.math.BigDecimal getAMT_GDSV_VAL()
    {
        
        return __AMT_GDSV_VAL;
    }
    
    /**
     * Set the value of AMT_GDSV_VAL  
     */
    public void setAMT_GDSV_VAL(java.math.BigDecimal value)
    {
        if ((__AMT_GDSV_VAL == null) != (value == null) || (value != null && ! value.equals(__AMT_GDSV_VAL)))
        {
            _isDirty = true;
        }
        __AMT_GDSV_VAL = value;
    }       
    /**
     * get the value of AMT_GDSV_CUR  
     */
    public java.lang.String getAMT_GDSV_CUR()
    {
        
        return __AMT_GDSV_CUR;
    }
    
    /**
     * Set the value of AMT_GDSV_CUR  
     */
    public void setAMT_GDSV_CUR(java.lang.String value)
    {
        if ((__AMT_GDSV_CUR == null) != (value == null) || (value != null && ! value.equals(__AMT_GDSV_CUR)))
        {
            _isDirty = true;
        }
        __AMT_GDSV_CUR = value;
    }       
    /**
     * get the value of ZADDSERV  
     */
    public java.lang.String getZADDSERV()
    {
        
        return __ZADDSERV;
    }
    
    /**
     * Set the value of ZADDSERV  
     */
    public void setZADDSERV(java.lang.String value)
    {
        if ((__ZADDSERV == null) != (value == null) || (value != null && ! value.equals(__ZADDSERV)))
        {
            _isDirty = true;
        }
        __ZADDSERV = value;
    }       
    /**
     * get the value of IV_FU_TOR_ID  
     */
    public java.lang.String getIV_FU_TOR_ID()
    {
        
        return __IV_FU_TOR_ID;
    }
    
    /**
     * Set the value of IV_FU_TOR_ID  
     */
    public void setIV_FU_TOR_ID(java.lang.String value)
    {
        if ((__IV_FU_TOR_ID == null) != (value == null) || (value != null && ! value.equals(__IV_FU_TOR_ID)))
        {
            _isDirty = true;
        }
        __IV_FU_TOR_ID = value;
    }       
    /**
     * get the value of IV_FO_TOR_ID  
     */
    public java.lang.String getIV_FO_TOR_ID()
    {
        
        return __IV_FO_TOR_ID;
    }
    
    /**
     * Set the value of IV_FO_TOR_ID  
     */
    public void setIV_FO_TOR_ID(java.lang.String value)
    {
        if ((__IV_FO_TOR_ID == null) != (value == null) || (value != null && ! value.equals(__IV_FO_TOR_ID)))
        {
            _isDirty = true;
        }
        __IV_FO_TOR_ID = value;
    }       
    /**
     * get the value of orders  
     */
    public ru.terralink.mvideo.sap.Orders getOrders()
    {
        if (! __ordersValid)
        {
            if( (__ordersFK != null))
            {
                __orders = ru.terralink.mvideo.sap.Orders.find(__ordersFK);
            }
            __ordersValid = true;
        }
        return __orders;
    }
    
    /**
     * Set the value of orders  
     */
    public void setOrders(ru.terralink.mvideo.sap.Orders value)
    {
        if (getOrders() != null)
        {
            if( !__orders.equals(value) )
            {
                _isDirty = true;
            }
        }
        else if(value != null)
        {
            _isDirty = true;
        }
        if(__orders != null)
        {
            __orders.setDirty(_isDirty);
        }
        if (value == null)
        {
            __ordersFK = null;
        }
        else
        {
            value.setDirty(_isDirty);
            __ordersFK = value._pk();
            __IV_FO_TOR_ID = value.getIV_FO_TOR_ID();
            __IV_FU_TOR_ID = value.getIV_FU_TOR_ID();
        }
        __ordersValid = true;
        __orders = value;
    }       
    /**
     * get the value of cvpOperation  
     */
    public com.sybase.persistence.BigString getCvpOperation()
    {
        
        if(__cvpOperation==null)
        {
        	__cvpOperation = new com.sybase.persistence.internal.BigStringImpl(this, "cvpOperation");
        }
        return __cvpOperation;
    }       
    /**
     * get the value of cvpOperationLobs  
     */
    public com.sybase.persistence.BigString getCvpOperationLobs()
    {
        
        if(__cvpOperationLobs==null)
        {
        	__cvpOperationLobs = new com.sybase.persistence.internal.BigStringImpl(this, "cvpOperationLobs");
        }
        return __cvpOperationLobs;
    }       
    /**
     * get the value of ordersFK  
     */
    public java.lang.Long getOrdersFK()
    {
        
        return __ordersFK;
    }
    
    /**
     * Set the value of ordersFK  
     */
    public void setOrdersFK(java.lang.Long value)
    {
        if ((__ordersFK == null) != (value == null) || (value != null && ! value.equals(__ordersFK)))
        {
            __ordersValid = false;
            _isDirty = true;
        }
        __ordersFK = value;
    }       
    /**
     * get the value of ordersValid  
     */
    private boolean getOrdersValid()
    {
        
        return __ordersValid;
    }
    
    /**
     * Set the value of ordersValid  
     */
    private void setOrdersValid(boolean value)
    {
        __ordersValid = value;
    }       
    /**
     * get the value of surrogateKey  
     */
    public long getSurrogateKey()
    {
        
        return __surrogateKey;
    }
    
    /**
     * Set the value of surrogateKey  
     */
    public void setSurrogateKey(long value)
    {
        if(__surrogateKey != value)
        {
            _isDirty = true;
        }
        __surrogateKey = value;
    }       
    /**
     * get the value of cvpOperationLength  
     */
    public long getCvpOperationLength()
    {
        
        return __cvpOperationLength;
    }
    
    /**
     * Set the value of cvpOperationLength  
     */
    public void setCvpOperationLength(long value)
    {
        if(__cvpOperationLength != value)
        {
            _isDirty = true;
        }
        __cvpOperationLength = value;
    }       
    /**
     * get the value of cvpOperationLobsLength  
     */
    public long getCvpOperationLobsLength()
    {
        
        return __cvpOperationLobsLength;
    }
    
    /**
     * Set the value of cvpOperationLobsLength  
     */
    public void setCvpOperationLobsLength(long value)
    {
        if(__cvpOperationLobsLength != value)
        {
            _isDirty = true;
        }
        __cvpOperationLobsLength = value;
    }
    
    /**
     * Search mobile business object using surrogateKey
     * @param id surrogateKey
     * @return mobile business object
     */
    public static ru.terralink.mvideo.sap.Products find(long id)
    {
        String intervalName = null;
        if(com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.isEnabled)
        {
            intervalName = "Products.find()";
            com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.getInstance().startInterval(intervalName, com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.PersistenceRead);
        }
        try
        {
            Object[] keys = new Object[]{id};
            return (ru.terralink.mvideo.sap.Products)(DELEGATE.findEntityWithKeys(keys));
        }
        finally
        {
            if(com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.isEnabled)
            {
                com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.getInstance().stopInterval(intervalName);
            }
        }
    }
    
    /**
     * Get the mobile business object by surrogate key.
     * @param id surrogate key
     * @return the mobile business object for the surroget key
     * @exception ObjectNotFoundException Thrown if unable to retrieve mobile business object.
     */
    public static ru.terralink.mvideo.sap.Products load(long id)
    {
        return (ru.terralink.mvideo.sap.Products)(DELEGATE.load(id));
    }
    
    /**
     * Get surroget key of the mobile business object  
     */
    public java.lang.Long _pk()
    {
        return (java.lang.Long)i_pk();
    }
    
    /** Begin code region: Finder methods **/
    /**
     * return MBO count filter by query object  
     */
    public static int getSize(com.sybase.persistence.Query query)
    {
        return DELEGATE.getSize(query);
    }
    
    /**
     * Find a List of Products
     * @param query The query to be filter.
     * @exception PersistenceException Thrown if unable to retrieve mobile business object.
     */
    public static com.sybase.collections.GenericList<ru.terralink.mvideo.sap.Products> findWithQuery(com.sybase.persistence.Query query)
    {
        return (com.sybase.collections.GenericList<ru.terralink.mvideo.sap.Products>)(Object)DELEGATE.findWithQuery(query, ru.terralink.mvideo.sap.Products.class);
    }
    
    /**
     * Find a List of Ru.terralink.mvideo.sap.Products
     * @exception PersistentException Thrown if unable to retrieve mobile business object.
     */
    public static com.sybase.collections.GenericList<ru.terralink.mvideo.sap.Products> findAll(int skip, int take)
    {
        String intervalName = null;
        if(com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.isEnabled)
        {
            intervalName = "Products.findAll";
            com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.getInstance().startInterval(intervalName, com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.PersistenceRead);
        }
        try
        {
            String _selectSQL = "select " + " x.\"a\",x.\"b\",x.\"c\",x.\"d\",x.\"e\",x.\"f\",x.\"g\",x.\"h\",x.\"i\",x.\"j\",x.\"l\",x.\"pending\",x.\"_pc\",x.\"_rp\",x.\"_rf\",x.\"ordersFK\",x.\"m\",x.\"_rc\",x.\"_ds\",x.\"cvpOperation_length\",x.\"cvpOperationLobs_length\" FROM \"mvideo5_1_0_products\" x where (((x.\"pending\" = 1 or not exists (select x_o"
                                                + "s.\"m\" from \"mvideo5_1_0_products_os\" x_os where x_os.\"m\" = x.\"m\"))))"; 
            return (com.sybase.collections.GenericList<ru.terralink.mvideo.sap.Products>)(Object)DELEGATE.findWithSQL(skip, take, _selectSQL, ru.terralink.mvideo.sap.Products.class);
        }
        finally
        {
            if(com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.isEnabled)
            {
                com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.getInstance().stopInterval(intervalName);
            }
        }
    }
    /**
     * Find a list of ru.terralink.mvideo.sap.Products  
     */
    public static com.sybase.collections.GenericList<ru.terralink.mvideo.sap.Products> findAll()
    {
        return findAll(0, Integer.MAX_VALUE);
    }
    /**
     * Find a mobile business object Ru.terralink.mvideo.sap.Products
     * @exception PersistentException Thrown if unable to retrieve mobile business object.
     */
    public static ru.terralink.mvideo.sap.Products findByPrimaryKey(java.lang.String TOR_ID)
    {
        String intervalName = null;
        if(com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.isEnabled)
        {
            intervalName = "Products.findByPrimaryKey";
            com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.getInstance().startInterval(intervalName, com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.PersistenceRead);
        }
        try
        {
    
            
                String _selectSQL = "SELECT x.\"a\",x.\"b\",x.\"c\",x.\"d\",x.\"e\",x.\"f\",x.\"g\",x.\"h\",x.\"i\",x.\"j\",x.\"l\",x.\"pending\",x.\"_pc\",x.\"_rp\",x.\"_rf\",x.\"ordersFK\",x.\"m\",x.\"_rc\",x.\"_ds\",x.\"cvpOperation_length\",x.\"cvpOperationLobs_length\" FROM \"mvideo5_1_0_products\" x WHERE (((x.\"pending\" = 1 or not exists (sele"
                                        + "ct x_os.\"m\" from \"mvideo5_1_0_products_os\" x_os where x_os.\"m\" = x.\"m\")))) and ( x.\"a\" = ?)";
                String[] ids = new String[0];
                com.sybase.reflection.DataType[] dts = new com.sybase.reflection.DataType[]{    
                    com.sybase.reflection.DataType.forName("string"),
                };
                Object[] values = new Object[] { 
                    TOR_ID,
                };
                Object res = DELEGATE.findWithSQL(_selectSQL, dts, values, ids, ru.terralink.mvideo.sap.Products.class);
                return (ru.terralink.mvideo.sap.Products)res;
        }
        finally
        {
            if(com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.isEnabled)
            {
                com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.getInstance().stopInterval(intervalName);
            }
        }
    }
    
    /**
     * Find a List of Ru.terralink.mvideo.sap.Products
     * @exception PersistentException Thrown if unable to retrieve mobile business object.
     */
    public static com.sybase.collections.GenericList<ru.terralink.mvideo.sap.Products> getOrdersProductss_for_Orders(java.lang.Long surrogateKey, int skip, int take)
    {
        String intervalName = null;
        if(com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.isEnabled)
        {
            intervalName = "Products.getOrdersProductss_for_Orders";
            com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.getInstance().startInterval(intervalName, com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.PersistenceRead);
        }
        try
        {
    
            
                String _selectSQL = " x.\"a\",x.\"b\",x.\"c\",x.\"d\",x.\"e\",x.\"f\",x.\"g\",x.\"h\",x.\"i\",x.\"j\",x.\"l\",x.\"pending\",x.\"_pc\",x.\"_rp\",x.\"_rf\",x.\"ordersFK\",x.\"m\",x.\"_rc\",x.\"_ds\",x.\"cvpOperation_length\",x.\"cvpOperationLobs_length\" from \"mvideo5_1_0_products\" x where (((x.\"pending\" = 1 or not exists (select x_o"
                                        + "s.\"m\" from \"mvideo5_1_0_products_os\" x_os where x_os.\"m\" = x.\"m\")))) and ( x.\"ordersFK\"=?)";
                _selectSQL = "select " + _selectSQL;
                String[] ids = new String[0];
                com.sybase.reflection.DataType[] dts = new com.sybase.reflection.DataType[]{    
                    com.sybase.reflection.DataType.forName("long?"),
                };
                Object[] values = new Object[] { 
                    surrogateKey,
                };
                com.sybase.collections.GenericList<Object> res = DELEGATE.findWithSQL(_selectSQL, dts, values, ids, skip, take, ru.terralink.mvideo.sap.Products.class);
                return (com.sybase.collections.GenericList<ru.terralink.mvideo.sap.Products>)(Object)res;
        }
        finally
        {
            if(com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.isEnabled)
            {
                com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.getInstance().stopInterval(intervalName);
            }
        }
    }
    /**
     * Find a list of ru.terralink.mvideo.sap.Products  
     */
    public static com.sybase.collections.GenericList<ru.terralink.mvideo.sap.Products> getOrdersProductss_for_Orders(java.lang.Long surrogateKey)
    {
        return getOrdersProductss_for_Orders(surrogateKey, 0, Integer.MAX_VALUE);
    }
    
    /**
     * Returns the MBOs that are updated locally but not submitted.  
     */
    public static com.sybase.collections.GenericList<ru.terralink.mvideo.sap.Products> getPendingObjects(int skip, int take)
    {
        return (com.sybase.collections.GenericList<ru.terralink.mvideo.sap.Products>)(Object)DELEGATE.getPendingObjects(skip, take);
    }
    
    /**
     * Returns the MBOs that are updated locally but not submmited.  
     */
    public static com.sybase.collections.GenericList<ru.terralink.mvideo.sap.Products> getPendingObjects()
    {
        return (com.sybase.collections.GenericList<ru.terralink.mvideo.sap.Products>)(Object)DELEGATE.getPendingObjects();
    }
    
    /** End code region: Finder methods **/
    /**
     * Returns the log record list.  
     */
    public com.sybase.collections.GenericList<com.sybase.persistence.LogRecord> getLogRecords()
    {
        return ru.terralink.mvideo.sap.LogRecordImpl.findByEntity("Products", keyToString());
    }
    
    
    
    
    
    public void create()
    {
        throw new com.sybase.persistence.NoSuchOperationException(com.sybase.persistence.NoSuchOperationException.NO_SUCH_OPERATION);
    }
    
    public void update()
    {
        throw new com.sybase.persistence.NoSuchOperationException(com.sybase.persistence.NoSuchOperationException.NO_SUCH_OPERATION);
    }      
    
    public void delete()
    {
        throw new com.sybase.persistence.NoSuchOperationException(com.sybase.persistence.NoSuchOperationException.NO_SUCH_OPERATION);
    }      
    
    
    
    
    /**
     * Submit pending operations of the mobile business object (ready for sending to server)  
     */
    public static void submitPendingOperations()
    {
        DELEGATE.submitPendingOperations();
    }
    
    /**
     * Cancel all the pending operations (not submitted operation).  
     */
    public static void cancelPendingOperations()
    {
        DELEGATE.cancelPendingOperations();
    }
    
    /**
     * Get the last called operation of the mobile business object  
     */
    public String getLastOperation()
    {
        if (!getCvpOperation().isNull())
        {
            com.sybase.afx.json.JsonObject cvpOperation = (com.sybase.afx.json.JsonObject)(com.sybase.afx.json.JsonReader.parse(__cvpOperation.getValue()));
            return (String)cvpOperation.get("cvp_name");
        }
        if (getPendingChange() == 'C')
        {
        }
        else if (getPendingChange() == 'D')
        {
        }
        else if (getPendingChange() == 'U')
        {
        }
        return null;
    }
    
    public ru.terralink.mvideo.sap.Products getDownloadState()
    {
        return (ru.terralink.mvideo.sap.Products)i_getDownloadState();
    }
    
    public ru.terralink.mvideo.sap.Products getOriginalState()
    {
        return (ru.terralink.mvideo.sap.Products)i_getOriginalState();
    }
    
    /**
     * Install a callback handler
     */
    public static void registerCallbackHandler(com.sybase.persistence.CallbackHandler handler)
    {
        DELEGATE.registerCallbackHandler(handler);
    }
    
    public static com.sybase.persistence.CallbackHandler getCallbackHandler()
    {
        return DELEGATE.getCallbackHandler();
    }
}