/**
 * Generated by Sybase AFX Compiler with templateJ
 * Compiler version - 2.3.0.183
 * mbs - false 
 */
package ru.terralink.mvideo.sap;

@SuppressWarnings("all")
public  class UpdateStatusSynchronizationParameters extends com.sybase.sup.client.persistence.AbstractSynchronizationParameters implements com.sybase.persistence.LocalBusinessObject, com.sybase.reflection.ClassWithMetaData
{
    /** Begin code region: MetaData **/
    private static ru.terralink.mvideo.sap.intrnl.UpdateStatusSynchronizationParametersMetaData META_DATA = new ru.terralink.mvideo.sap.intrnl.UpdateStatusSynchronizationParametersMetaData();
    
    /**
     * return MetaData object  
     */
    public com.sybase.reflection.ClassMetaData getClassMetaData()
    {
        return META_DATA;
    }
    
    /**
     * return MetaData object  
     */
    public static com.sybase.reflection.EntityMetaData getMetaData()
    {
        return META_DATA;
    }
    
    /** End code region: MetaData **/
    protected static com.sybase.sup.client.persistence.SyncParamEntityDelegate DELEGATE = 
        com.sybase.sup.client.persistence.DelegateFactory.createSyncParamEntityDelegate("UpdateStatusSynchronizationParameters", ru.terralink.mvideo.sap.UpdateStatusSynchronizationParameters.class, META_DATA, ru.terralink.mvideo.sap.Mvideo5DB.getDelegate());
    
    
    /** Begin code region: Properties **/
    private java.lang.String __sp_code ;
    
    private boolean __sp_codeUserDefined ;
    
    private java.lang.String __sp_comment ;
    
    private boolean __sp_commentUserDefined ;
    
    private java.lang.String __sp_fo ;
    
    private boolean __sp_foUserDefined ;
    
    private java.lang.String __sp_fu ;
    
    private boolean __sp_fuUserDefined ;
    
    public java.lang.String getAttributeNullableString(int id)
    {
        switch(id)
        {
        case 556:
            return getSp_code();
        case 558:
            return getSp_comment();
        case 560:
            return getSp_fo();
        case 562:
            return getSp_fu();
        default:
            return super.getAttributeNullableString(id);
        }
    }
    
    public void setAttributeNullableString(int id, java.lang.String v)
    {
        switch(id)
        {
        case 556:
            setSp_code((java.lang.String)v);
            break;
        case 558:
            setSp_comment((java.lang.String)v);
            break;
        case 560:
            setSp_fo((java.lang.String)v);
            break;
        case 562:
            setSp_fu((java.lang.String)v);
            break;
        default:
            super.setAttributeNullableString(id, v);
            break;
        }
    }
    public java.lang.String getAttributeString(int id)
    {
        switch(id)
        {
        case 564:
            return getUser_sp();
        default:
            return super.getAttributeString(id);
        }
    }
    
    public void setAttributeString(int id, java.lang.String v)
    {
        switch(id)
        {
        case 564:
            setUser_sp((java.lang.String)v);
            break;
        default:
            super.setAttributeString(id, v);
            break;
        }
    }
    public int getAttributeInt(int id)
    {
        switch(id)
        {
        case 565:
            return getSize_sp();
        default:
            return super.getAttributeInt(id);
        }
    }
    
    public void setAttributeInt(int id, int v)
    {
        switch(id)
        {
        case 565:
            setSize_sp((int)v);
            break;
        default:
            super.setAttributeInt(id, v);
            break;
        }
    }
    public boolean getAttributeBoolean(int id)
    {
        switch(id)
        {
        case 557:
            return getSp_codeUserDefined();
        case 559:
            return getSp_commentUserDefined();
        case 561:
            return getSp_foUserDefined();
        case 563:
            return getSp_fuUserDefined();
        default:
            return super.getAttributeBoolean(id);
        }
    }
    
    public void setAttributeBoolean(int id, boolean v)
    {
        switch(id)
        {
        case 557:
            setSp_codeUserDefined((boolean)v);
            break;
        case 559:
            setSp_commentUserDefined((boolean)v);
            break;
        case 561:
            setSp_foUserDefined((boolean)v);
            break;
        case 563:
            setSp_fuUserDefined((boolean)v);
            break;
        default:
            super.setAttributeBoolean(id, v);
            break;
        }
    }
    
    public Object getAttributeJson(int id)
    {
        switch(id)
        {
        default:
            return super.getAttributeJson(id);
        }
    }
    
    public void setAttributeJson(int id, Object value)
    {
        switch(id)
        {
        default:
            super.setAttributeJson(id, value);
            break;
        }
    }
    /** End code region: Properties **/
    
    /** Begin code region: Constructor and init **/
    /**
     * Creates an instance of ru.terralink.mvideo.sap.UpdateStatusSynchronizationParameters  
     */
    public UpdateStatusSynchronizationParameters()
    {
        setEntityDelegate(DELEGATE);
        persistentQueryDelegate = ru.terralink.mvideo.sap.intrnl.UpdateStatus_pull_pq.getEntityDelegateForPQ();
        _init();
    }
    protected void _init()
    {
        
    }
    /** End code region: Constructor and init **/
    
    /**
     * get the value of sp_code  
     */
    public java.lang.String getSp_code()
    {
        
        return __sp_code;
    }
    
    /**
     * Set the value of sp_code  
     */
    public void setSp_code(java.lang.String value)
    {
        if ((__sp_code == null) != (value == null) || (value != null && ! value.equals(__sp_code)))
        {
            _isDirty = true;
        }
        if ( __sp_codeUserDefined == false )
        {
            __sp_codeUserDefined = true;
            _isDirty = true;
        }
        __sp_code = value;
        if ( __sp_codeUserDefined == false )
        {
            __sp_codeUserDefined = true;
        }
    }
    /**
     * get the value of sp_codeUserDefined  
     */
    public boolean getSp_codeUserDefined()
    {
        
        return __sp_codeUserDefined;
    }
    
    /**
     * Set the value of sp_codeUserDefined  
     */
    private void setSp_codeUserDefined(boolean value)
    {
        if(__sp_codeUserDefined != value)
        {
            _isDirty = true;
        }
        __sp_codeUserDefined = value;
    }
    /**
     * get the value of sp_comment  
     */
    public java.lang.String getSp_comment()
    {
        
        return __sp_comment;
    }
    
    /**
     * Set the value of sp_comment  
     */
    public void setSp_comment(java.lang.String value)
    {
        if ((__sp_comment == null) != (value == null) || (value != null && ! value.equals(__sp_comment)))
        {
            _isDirty = true;
        }
        if ( __sp_commentUserDefined == false )
        {
            __sp_commentUserDefined = true;
            _isDirty = true;
        }
        __sp_comment = value;
        if ( __sp_commentUserDefined == false )
        {
            __sp_commentUserDefined = true;
        }
    }
    /**
     * get the value of sp_commentUserDefined  
     */
    public boolean getSp_commentUserDefined()
    {
        
        return __sp_commentUserDefined;
    }
    
    /**
     * Set the value of sp_commentUserDefined  
     */
    private void setSp_commentUserDefined(boolean value)
    {
        if(__sp_commentUserDefined != value)
        {
            _isDirty = true;
        }
        __sp_commentUserDefined = value;
    }
    /**
     * get the value of sp_fo  
     */
    public java.lang.String getSp_fo()
    {
        
        return __sp_fo;
    }
    
    /**
     * Set the value of sp_fo  
     */
    public void setSp_fo(java.lang.String value)
    {
        if ((__sp_fo == null) != (value == null) || (value != null && ! value.equals(__sp_fo)))
        {
            _isDirty = true;
        }
        if ( __sp_foUserDefined == false )
        {
            __sp_foUserDefined = true;
            _isDirty = true;
        }
        __sp_fo = value;
        if ( __sp_foUserDefined == false )
        {
            __sp_foUserDefined = true;
        }
    }
    /**
     * get the value of sp_foUserDefined  
     */
    public boolean getSp_foUserDefined()
    {
        
        return __sp_foUserDefined;
    }
    
    /**
     * Set the value of sp_foUserDefined  
     */
    private void setSp_foUserDefined(boolean value)
    {
        if(__sp_foUserDefined != value)
        {
            _isDirty = true;
        }
        __sp_foUserDefined = value;
    }
    /**
     * get the value of sp_fu  
     */
    public java.lang.String getSp_fu()
    {
        
        return __sp_fu;
    }
    
    /**
     * Set the value of sp_fu  
     */
    public void setSp_fu(java.lang.String value)
    {
        if ((__sp_fu == null) != (value == null) || (value != null && ! value.equals(__sp_fu)))
        {
            _isDirty = true;
        }
        if ( __sp_fuUserDefined == false )
        {
            __sp_fuUserDefined = true;
            _isDirty = true;
        }
        __sp_fu = value;
        if ( __sp_fuUserDefined == false )
        {
            __sp_fuUserDefined = true;
        }
    }
    /**
     * get the value of sp_fuUserDefined  
     */
    public boolean getSp_fuUserDefined()
    {
        
        return __sp_fuUserDefined;
    }
    
    /**
     * Set the value of sp_fuUserDefined  
     */
    private void setSp_fuUserDefined(boolean value)
    {
        if(__sp_fuUserDefined != value)
        {
            _isDirty = true;
        }
        __sp_fuUserDefined = value;
    }
    
    /**
     * Search mobile business object using surrogateKey
     * @param id surrogateKey
     * @return mobile business object
     */
    public static ru.terralink.mvideo.sap.UpdateStatusSynchronizationParameters find(java.lang.String id)
    {
        String intervalName = null;
        if(com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.isEnabled)
        {
            intervalName = "UpdateStatusSynchronizationParameters.find()";
            com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.getInstance().startInterval(intervalName, com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.PersistenceRead);
        }
        try
        {
            Object[] keys = new Object[]{id};
            return (ru.terralink.mvideo.sap.UpdateStatusSynchronizationParameters)(DELEGATE.findEntityWithKeys(keys));
        }
        finally
        {
            if(com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.isEnabled)
            {
                com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.getInstance().stopInterval(intervalName);
            }
        }
    }
    
    /**
     * Get the mobile business object by surrogate key.
     * @param id surrogate key
     * @return the mobile business object for the surroget key
     * @exception ObjectNotFoundException Thrown if unable to retrieve mobile business object.
     */
    public static ru.terralink.mvideo.sap.UpdateStatusSynchronizationParameters load(java.lang.String id)
    {
        return (ru.terralink.mvideo.sap.UpdateStatusSynchronizationParameters)(DELEGATE.load(id));
    }
    
    /**
     * Get surroget key of the mobile business object  
     */
    public java.lang.String _pk()
    {
        return (java.lang.String)i_pk();
    }
    
    /** Begin code region: Finder methods **/
    
    
    
    /** End code region: Finder methods **/
}