/**
 * Generated by Sybase AFX Compiler with templateJ
 * Compiler version - 2.3.0.183
 * mbs - false 
 */
package ru.terralink.mvideo.sap;

@SuppressWarnings("all")
public  class UpdateStatusSubscription extends com.sybase.persistence.AbstractStructure 
{
    private java.lang.String __sp_code ;  
    
    private java.lang.String __sp_comment ;  
    
    private java.lang.String __sp_fo ;  
    
    private java.lang.String __sp_fu ;  
    
    public java.lang.String getAttributeNullableString(int id)
    {
        switch(id)
        {
        case 551:
            return getSp_code();
        case 552:
            return getSp_comment();
        case 553:
            return getSp_fo();
        case 554:
            return getSp_fu();
        default:
            return super.getAttributeNullableString(id);
        }
    }
    
    public void setAttributeNullableString(int id, java.lang.String v)
    {
        switch(id)
        {
        case 551:
            setSp_code((java.lang.String)v);
            break;
        case 552:
            setSp_comment((java.lang.String)v);
            break;
        case 553:
            setSp_fo((java.lang.String)v);
            break;
        case 554:
            setSp_fu((java.lang.String)v);
            break;
        default:
            super.setAttributeNullableString(id, v);
            break;
        }
    }
    
    public Object getAttributeJson(int id)
    {
        switch(id)
        {
        default:
            return super.getAttributeJson(id);
        }
    }
    
    public void setAttributeJson(int id, Object value)
    {
        switch(id)
        {
        default:
            super.setAttributeJson(id, value);
            break;
        }
    }
    
    private boolean _userDefinedForSp_code = false;
    /**
     * get the value of sp_code  
     */
    public java.lang.String getSp_code()
    {
        if (!_userDefinedForSp_code)
        {
            ru.terralink.mvideo.sap.intrnl.UpdateStatus_pull_pq pq = new ru.terralink.mvideo.sap.intrnl.UpdateStatus_pull_pq();
            java.lang.String result = pq.getSp_codeParam();
            return result;
        }
        return __sp_code;
    }
    
    /**
     * Set the value of sp_code  
     */
    public void setSp_code(java.lang.String value)
    {
        __sp_code = value;  
        _userDefinedForSp_code = true;
    }
    
    private boolean _userDefinedForSp_comment = false;
    /**
     * get the value of sp_comment  
     */
    public java.lang.String getSp_comment()
    {
        if (!_userDefinedForSp_comment)
        {
            ru.terralink.mvideo.sap.intrnl.UpdateStatus_pull_pq pq = new ru.terralink.mvideo.sap.intrnl.UpdateStatus_pull_pq();
            java.lang.String result = pq.getSp_commentParam();
            return result;
        }
        return __sp_comment;
    }
    
    /**
     * Set the value of sp_comment  
     */
    public void setSp_comment(java.lang.String value)
    {
        __sp_comment = value;  
        _userDefinedForSp_comment = true;
    }
    
    private boolean _userDefinedForSp_fo = false;
    /**
     * get the value of sp_fo  
     */
    public java.lang.String getSp_fo()
    {
        if (!_userDefinedForSp_fo)
        {
            ru.terralink.mvideo.sap.intrnl.UpdateStatus_pull_pq pq = new ru.terralink.mvideo.sap.intrnl.UpdateStatus_pull_pq();
            java.lang.String result = pq.getSp_foParam();
            return result;
        }
        return __sp_fo;
    }
    
    /**
     * Set the value of sp_fo  
     */
    public void setSp_fo(java.lang.String value)
    {
        __sp_fo = value;  
        _userDefinedForSp_fo = true;
    }
    
    private boolean _userDefinedForSp_fu = false;
    /**
     * get the value of sp_fu  
     */
    public java.lang.String getSp_fu()
    {
        if (!_userDefinedForSp_fu)
        {
            ru.terralink.mvideo.sap.intrnl.UpdateStatus_pull_pq pq = new ru.terralink.mvideo.sap.intrnl.UpdateStatus_pull_pq();
            java.lang.String result = pq.getSp_fuParam();
            return result;
        }
        return __sp_fu;
    }
    
    /**
     * Set the value of sp_fu  
     */
    public void setSp_fu(java.lang.String value)
    {
        __sp_fu = value;  
        _userDefinedForSp_fu = true;
    }
}