/**
 * Generated by Sybase AFX Compiler with templateJ
 * Compiler version - 2.3.0.183
 * mbs - false 
 */
package ru.terralink.mvideo.sap;

@SuppressWarnings("all")
public  class UpdateStatus extends com.sybase.persistence.AbstractEntity implements com.sybase.persistence.MobileBusinessObject, com.sybase.reflection.ClassWithMetaData
{
    /** Begin code region: MetaData **/
    private static ru.terralink.mvideo.sap.intrnl.UpdateStatusMetaData META_DATA = new ru.terralink.mvideo.sap.intrnl.UpdateStatusMetaData();
    
    /**
     * return MetaData object  
     */
    public com.sybase.reflection.ClassMetaData getClassMetaData()
    {
        return META_DATA;
    }
    
    /**
     * return MetaData object  
     */
    public static com.sybase.reflection.EntityMetaData getMetaData()
    {
        return META_DATA;
    }
    
    /** End code region: MetaData **/
    protected static com.sybase.sup.client.persistence.EntityDelegate DELEGATE = 
        com.sybase.sup.client.persistence.DelegateFactory.createEntityDelegate("UpdateStatus", ru.terralink.mvideo.sap.UpdateStatus.class, "mvideo5.UpdateStatus", META_DATA, ru.terralink.mvideo.sap.Mvideo5DB.getDelegate());
    
    
    /** Begin code region: Properties **/
    private java.lang.String __TYPE ;  
    
    private java.lang.String __ID ;  
    
    private java.lang.String __NUMBER ;  
    
    private java.lang.String __MESSAGE ;  
    
    private java.lang.String __LOG_NO ;  
    
    private java.lang.String __LOG_MSG_NO ;  
    
    private java.lang.String __MESSAGE_V1 ;  
    
    private java.lang.String __MESSAGE_V2 ;  
    
    private java.lang.String __MESSAGE_V3 ;  
    
    private java.lang.String __MESSAGE_V4 ;  
    
    private java.lang.String __PARAMETER ;  
    
    private int __ROW ;  
    
    private java.lang.String __FIELD ;  
    
    private java.lang.String __SYSTEM ;  
    
      
    
      
    
      
    
      
    
    private com.sybase.persistence.BigString __cvpOperation ;  
    
    private com.sybase.persistence.BigString __cvpOperationLobs ;  
    
    private long __surrogateKey ;  
    
      
    
      
    
    private long __cvpOperationLength ;  
    
    private long __cvpOperationLobsLength ;  
    
    public long getAttributeLong(int id)
    {
        switch(id)
        {
        case 297:
            return getSurrogateKey();
        case 1373:
            return getCvpOperationLength();
        case 1374:
            return getCvpOperationLobsLength();
        default:
            return super.getAttributeLong(id);
        }
    }
    
    public void setAttributeLong(int id, long v)
    {
        switch(id)
        {
        case 297:
            setSurrogateKey((long)v);
            break;
        case 1373:
            setCvpOperationLength((long)v);
            break;
        case 1374:
            setCvpOperationLobsLength((long)v);
            break;
        default:
            super.setAttributeLong(id, v);
            break;
        }
    }
    public com.sybase.persistence.BigString getAttributeNullableBigString(int id)
    {
        switch(id)
        {
        case 904:
            return getCvpOperation();
        case 905:
            return getCvpOperationLobs();
        default:
            return super.getAttributeNullableBigString(id);
        }
    }
    
    public java.lang.String getAttributeString(int id)
    {
        switch(id)
        {
        case 283:
            return getTYPE();
        case 284:
            return getID();
        case 285:
            return getNUMBER();
        case 286:
            return getMESSAGE();
        case 287:
            return getLOG_NO();
        case 288:
            return getLOG_MSG_NO();
        case 289:
            return getMESSAGE_V1();
        case 290:
            return getMESSAGE_V2();
        case 291:
            return getMESSAGE_V3();
        case 292:
            return getMESSAGE_V4();
        case 293:
            return getPARAMETER();
        case 295:
            return getFIELD();
        case 296:
            return getSYSTEM();
        default:
            return super.getAttributeString(id);
        }
    }
    
    public void setAttributeString(int id, java.lang.String v)
    {
        switch(id)
        {
        case 283:
            setTYPE((java.lang.String)v);
            break;
        case 284:
            setID((java.lang.String)v);
            break;
        case 285:
            setNUMBER((java.lang.String)v);
            break;
        case 286:
            setMESSAGE((java.lang.String)v);
            break;
        case 287:
            setLOG_NO((java.lang.String)v);
            break;
        case 288:
            setLOG_MSG_NO((java.lang.String)v);
            break;
        case 289:
            setMESSAGE_V1((java.lang.String)v);
            break;
        case 290:
            setMESSAGE_V2((java.lang.String)v);
            break;
        case 291:
            setMESSAGE_V3((java.lang.String)v);
            break;
        case 292:
            setMESSAGE_V4((java.lang.String)v);
            break;
        case 293:
            setPARAMETER((java.lang.String)v);
            break;
        case 295:
            setFIELD((java.lang.String)v);
            break;
        case 296:
            setSYSTEM((java.lang.String)v);
            break;
        default:
            super.setAttributeString(id, v);
            break;
        }
    }
    public int getAttributeInt(int id)
    {
        switch(id)
        {
        case 294:
            return getROW();
        default:
            return super.getAttributeInt(id);
        }
    }
    
    public void setAttributeInt(int id, int v)
    {
        switch(id)
        {
        case 294:
            setROW((int)v);
            break;
        default:
            super.setAttributeInt(id, v);
            break;
        }
    }
    
    public Object getAttributeJson(int id)
    {
        switch(id)
        {
        default:
            return super.getAttributeJson(id);
        }
    }
    
    public void setAttributeJson(int id, Object value)
    {
        switch(id)
        {
        default:
            super.setAttributeJson(id, value);
            break;
        }
    }
    /** End code region: Properties **/
    
    /** Begin code region: Constructor and init **/
    /**
     * Creates an instance of ru.terralink.mvideo.sap.UpdateStatus  
     */
    public UpdateStatus()
    {
        setEntityDelegate(DELEGATE);
        _init();
    }
    protected void _init()
    {
        
    }
    /** End code region: Constructor and init **/
    
    /**
     * get the value of TYPE  
     */
    public java.lang.String getTYPE()
    {
        
        return __TYPE;
    }
    
    /**
     * Set the value of TYPE  
     */
    public void setTYPE(java.lang.String value)
    {
        if ((__TYPE == null) != (value == null) || (value != null && ! value.equals(__TYPE)))
        {
            _isDirty = true;
        }
        __TYPE = value;
    }       
    /**
     * get the value of ID  
     */
    public java.lang.String getID()
    {
        
        return __ID;
    }
    
    /**
     * Set the value of ID  
     */
    public void setID(java.lang.String value)
    {
        if ((__ID == null) != (value == null) || (value != null && ! value.equals(__ID)))
        {
            _isDirty = true;
        }
        __ID = value;
    }       
    /**
     * get the value of NUMBER  
     */
    public java.lang.String getNUMBER()
    {
        
        return __NUMBER;
    }
    
    /**
     * Set the value of NUMBER  
     */
    public void setNUMBER(java.lang.String value)
    {
        if ((__NUMBER == null) != (value == null) || (value != null && ! value.equals(__NUMBER)))
        {
            _isDirty = true;
        }
        __NUMBER = value;
    }       
    /**
     * get the value of MESSAGE  
     */
    public java.lang.String getMESSAGE()
    {
        
        return __MESSAGE;
    }
    
    /**
     * Set the value of MESSAGE  
     */
    public void setMESSAGE(java.lang.String value)
    {
        if ((__MESSAGE == null) != (value == null) || (value != null && ! value.equals(__MESSAGE)))
        {
            _isDirty = true;
        }
        __MESSAGE = value;
    }       
    /**
     * get the value of LOG_NO  
     */
    public java.lang.String getLOG_NO()
    {
        
        return __LOG_NO;
    }
    
    /**
     * Set the value of LOG_NO  
     */
    public void setLOG_NO(java.lang.String value)
    {
        if ((__LOG_NO == null) != (value == null) || (value != null && ! value.equals(__LOG_NO)))
        {
            _isDirty = true;
        }
        __LOG_NO = value;
    }       
    /**
     * get the value of LOG_MSG_NO  
     */
    public java.lang.String getLOG_MSG_NO()
    {
        
        return __LOG_MSG_NO;
    }
    
    /**
     * Set the value of LOG_MSG_NO  
     */
    public void setLOG_MSG_NO(java.lang.String value)
    {
        if ((__LOG_MSG_NO == null) != (value == null) || (value != null && ! value.equals(__LOG_MSG_NO)))
        {
            _isDirty = true;
        }
        __LOG_MSG_NO = value;
    }       
    /**
     * get the value of MESSAGE_V1  
     */
    public java.lang.String getMESSAGE_V1()
    {
        
        return __MESSAGE_V1;
    }
    
    /**
     * Set the value of MESSAGE_V1  
     */
    public void setMESSAGE_V1(java.lang.String value)
    {
        if ((__MESSAGE_V1 == null) != (value == null) || (value != null && ! value.equals(__MESSAGE_V1)))
        {
            _isDirty = true;
        }
        __MESSAGE_V1 = value;
    }       
    /**
     * get the value of MESSAGE_V2  
     */
    public java.lang.String getMESSAGE_V2()
    {
        
        return __MESSAGE_V2;
    }
    
    /**
     * Set the value of MESSAGE_V2  
     */
    public void setMESSAGE_V2(java.lang.String value)
    {
        if ((__MESSAGE_V2 == null) != (value == null) || (value != null && ! value.equals(__MESSAGE_V2)))
        {
            _isDirty = true;
        }
        __MESSAGE_V2 = value;
    }       
    /**
     * get the value of MESSAGE_V3  
     */
    public java.lang.String getMESSAGE_V3()
    {
        
        return __MESSAGE_V3;
    }
    
    /**
     * Set the value of MESSAGE_V3  
     */
    public void setMESSAGE_V3(java.lang.String value)
    {
        if ((__MESSAGE_V3 == null) != (value == null) || (value != null && ! value.equals(__MESSAGE_V3)))
        {
            _isDirty = true;
        }
        __MESSAGE_V3 = value;
    }       
    /**
     * get the value of MESSAGE_V4  
     */
    public java.lang.String getMESSAGE_V4()
    {
        
        return __MESSAGE_V4;
    }
    
    /**
     * Set the value of MESSAGE_V4  
     */
    public void setMESSAGE_V4(java.lang.String value)
    {
        if ((__MESSAGE_V4 == null) != (value == null) || (value != null && ! value.equals(__MESSAGE_V4)))
        {
            _isDirty = true;
        }
        __MESSAGE_V4 = value;
    }       
    /**
     * get the value of PARAMETER  
     */
    public java.lang.String getPARAMETER()
    {
        
        return __PARAMETER;
    }
    
    /**
     * Set the value of PARAMETER  
     */
    public void setPARAMETER(java.lang.String value)
    {
        if ((__PARAMETER == null) != (value == null) || (value != null && ! value.equals(__PARAMETER)))
        {
            _isDirty = true;
        }
        __PARAMETER = value;
    }       
    /**
     * get the value of ROW  
     */
    public int getROW()
    {
        
        return __ROW;
    }
    
    /**
     * Set the value of ROW  
     */
    public void setROW(int value)
    {
        if(__ROW != value)
        {
            _isDirty = true;
        }
        __ROW = value;
    }       
    /**
     * get the value of FIELD  
     */
    public java.lang.String getFIELD()
    {
        
        return __FIELD;
    }
    
    /**
     * Set the value of FIELD  
     */
    public void setFIELD(java.lang.String value)
    {
        if ((__FIELD == null) != (value == null) || (value != null && ! value.equals(__FIELD)))
        {
            _isDirty = true;
        }
        __FIELD = value;
    }       
    /**
     * get the value of SYSTEM  
     */
    public java.lang.String getSYSTEM()
    {
        
        return __SYSTEM;
    }
    
    /**
     * Set the value of SYSTEM  
     */
    public void setSYSTEM(java.lang.String value)
    {
        if ((__SYSTEM == null) != (value == null) || (value != null && ! value.equals(__SYSTEM)))
        {
            _isDirty = true;
        }
        __SYSTEM = value;
    }       
    /**
     * get the value of cvpOperation  
     */
    public com.sybase.persistence.BigString getCvpOperation()
    {
        
        if(__cvpOperation==null)
        {
        	__cvpOperation = new com.sybase.persistence.internal.BigStringImpl(this, "cvpOperation");
        }
        return __cvpOperation;
    }       
    /**
     * get the value of cvpOperationLobs  
     */
    public com.sybase.persistence.BigString getCvpOperationLobs()
    {
        
        if(__cvpOperationLobs==null)
        {
        	__cvpOperationLobs = new com.sybase.persistence.internal.BigStringImpl(this, "cvpOperationLobs");
        }
        return __cvpOperationLobs;
    }       
    /**
     * get the value of surrogateKey  
     */
    public long getSurrogateKey()
    {
        
        return __surrogateKey;
    }
    
    /**
     * Set the value of surrogateKey  
     */
    public void setSurrogateKey(long value)
    {
        if(__surrogateKey != value)
        {
            _isDirty = true;
        }
        __surrogateKey = value;
    }       
    /**
     * get the value of cvpOperationLength  
     */
    public long getCvpOperationLength()
    {
        
        return __cvpOperationLength;
    }
    
    /**
     * Set the value of cvpOperationLength  
     */
    public void setCvpOperationLength(long value)
    {
        if(__cvpOperationLength != value)
        {
            _isDirty = true;
        }
        __cvpOperationLength = value;
    }       
    /**
     * get the value of cvpOperationLobsLength  
     */
    public long getCvpOperationLobsLength()
    {
        
        return __cvpOperationLobsLength;
    }
    
    /**
     * Set the value of cvpOperationLobsLength  
     */
    public void setCvpOperationLobsLength(long value)
    {
        if(__cvpOperationLobsLength != value)
        {
            _isDirty = true;
        }
        __cvpOperationLobsLength = value;
    }
    
    /**
     * Search mobile business object using surrogateKey
     * @param id surrogateKey
     * @return mobile business object
     */
    public static ru.terralink.mvideo.sap.UpdateStatus find(long id)
    {
        String intervalName = null;
        if(com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.isEnabled)
        {
            intervalName = "UpdateStatus.find()";
            com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.getInstance().startInterval(intervalName, com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.PersistenceRead);
        }
        try
        {
            Object[] keys = new Object[]{id};
            return (ru.terralink.mvideo.sap.UpdateStatus)(DELEGATE.findEntityWithKeys(keys));
        }
        finally
        {
            if(com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.isEnabled)
            {
                com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.getInstance().stopInterval(intervalName);
            }
        }
    }
    
    /**
     * Get the mobile business object by surrogate key.
     * @param id surrogate key
     * @return the mobile business object for the surroget key
     * @exception ObjectNotFoundException Thrown if unable to retrieve mobile business object.
     */
    public static ru.terralink.mvideo.sap.UpdateStatus load(long id)
    {
        return (ru.terralink.mvideo.sap.UpdateStatus)(DELEGATE.load(id));
    }
    
    /**
     * Get surroget key of the mobile business object  
     */
    public java.lang.Long _pk()
    {
        return (java.lang.Long)i_pk();
    }
    
    /** Begin code region: Finder methods **/
    /**
     * return MBO count filter by query object  
     */
    public static int getSize(com.sybase.persistence.Query query)
    {
        return DELEGATE.getSize(query);
    }
    
    /**
     * Find a List of UpdateStatus
     * @param query The query to be filter.
     * @exception PersistenceException Thrown if unable to retrieve mobile business object.
     */
    public static com.sybase.collections.GenericList<ru.terralink.mvideo.sap.UpdateStatus> findWithQuery(com.sybase.persistence.Query query)
    {
        return (com.sybase.collections.GenericList<ru.terralink.mvideo.sap.UpdateStatus>)(Object)DELEGATE.findWithQuery(query, ru.terralink.mvideo.sap.UpdateStatus.class);
    }
    
    /**
     * Find a List of Ru.terralink.mvideo.sap.UpdateStatus
     * @exception PersistentException Thrown if unable to retrieve mobile business object.
     */
    public static com.sybase.collections.GenericList<ru.terralink.mvideo.sap.UpdateStatus> findAll(int skip, int take)
    {
        String intervalName = null;
        if(com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.isEnabled)
        {
            intervalName = "UpdateStatus.findAll";
            com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.getInstance().startInterval(intervalName, com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.PersistenceRead);
        }
        try
        {
            String _selectSQL = "select " + " x.\"a\",x.\"b\",x.\"c\",x.\"d\",x.\"e\",x.\"f\",x.\"g\",x.\"h\",x.\"i\",x.\"j\",x.\"l\",x.\"m\",x.\"n\",x.\"o\",x.\"pending\",x.\"_pc\",x.\"_rp\",x.\"_rf\",x.\"p\",x.\"_rc\",x.\"_ds\",x.\"cvpOperation_length\",x.\"cvpOperationLobs_length\" FROM \"mvideo5_1_0_updatestatus\" x where (((x.\"pending\" = 1 or not exists (s"
                                                + "elect x_os.\"p\" from \"mvideo5_1_0_updatestatus_os\" x_os where x_os.\"p\" = x.\"p\"))))"; 
            return (com.sybase.collections.GenericList<ru.terralink.mvideo.sap.UpdateStatus>)(Object)DELEGATE.findWithSQL(skip, take, _selectSQL, ru.terralink.mvideo.sap.UpdateStatus.class);
        }
        finally
        {
            if(com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.isEnabled)
            {
                com.sybase.mobile.util.perf.impl.PerformanceAgentServiceImpl.getInstance().stopInterval(intervalName);
            }
        }
    }
    /**
     * Find a list of ru.terralink.mvideo.sap.UpdateStatus  
     */
    public static com.sybase.collections.GenericList<ru.terralink.mvideo.sap.UpdateStatus> findAll()
    {
        return findAll(0, Integer.MAX_VALUE);
    }
    
    /**
     * Returns the MBOs that are updated locally but not submitted.  
     */
    public static com.sybase.collections.GenericList<ru.terralink.mvideo.sap.UpdateStatus> getPendingObjects(int skip, int take)
    {
        return (com.sybase.collections.GenericList<ru.terralink.mvideo.sap.UpdateStatus>)(Object)DELEGATE.getPendingObjects(skip, take);
    }
    
    /**
     * Returns the MBOs that are updated locally but not submmited.  
     */
    public static com.sybase.collections.GenericList<ru.terralink.mvideo.sap.UpdateStatus> getPendingObjects()
    {
        return (com.sybase.collections.GenericList<ru.terralink.mvideo.sap.UpdateStatus>)(Object)DELEGATE.getPendingObjects();
    }
    
    /** End code region: Finder methods **/
    /**
     * Returns the log record list.  
     */
    public com.sybase.collections.GenericList<com.sybase.persistence.LogRecord> getLogRecords()
    {
        return ru.terralink.mvideo.sap.LogRecordImpl.findByEntity("UpdateStatus", keyToString());
    }
    
    
    
    
    
    public void create()
    {
        throw new com.sybase.persistence.NoSuchOperationException(com.sybase.persistence.NoSuchOperationException.NO_SUCH_OPERATION);
    }
    
    public void update()
    {
        throw new com.sybase.persistence.NoSuchOperationException(com.sybase.persistence.NoSuchOperationException.NO_SUCH_OPERATION);
    }      
    
    public void delete()
    {
        throw new com.sybase.persistence.NoSuchOperationException(com.sybase.persistence.NoSuchOperationException.NO_SUCH_OPERATION);
    }      
    
    /**
     * @deprecated  
     */
    public static ru.terralink.mvideo.sap.UpdateStatusSynchronizationParameters getSynchronizationParameters()
    {   
        return (ru.terralink.mvideo.sap.UpdateStatusSynchronizationParameters)((com.sybase.sup.client.persistence.SyncParamEntityDelegate)(ru.terralink.mvideo.sap.Mvideo5DB.getDelegate().getEntityDelegate("UpdateStatusSynchronizationParameters"))).getSynchronizationParameters();
    }
    
    /**
     * Gets all EntitySubscriptions for the mobile entity  
     */
    public static com.sybase.collections.GenericList<ru.terralink.mvideo.sap.UpdateStatusSubscription> getSubscriptions()
    {
        com.sybase.collections.GenericList<ru.terralink.mvideo.sap.UpdateStatusSubscription> result = new com.sybase.collections.GenericList<ru.terralink.mvideo.sap.UpdateStatusSubscription>();
        for (ru.terralink.mvideo.sap.intrnl.UpdateStatus_pull_pq pq : ru.terralink.mvideo.sap.intrnl.UpdateStatus_pull_pq.findAll())    
        {
            ru.terralink.mvideo.sap.UpdateStatusSubscription subscription = new ru.terralink.mvideo.sap.UpdateStatusSubscription();
            subscription.setSp_code(pq.getSp_codeParam());    
            subscription.setSp_comment(pq.getSp_commentParam());    
            subscription.setSp_fo(pq.getSp_foParam());    
            subscription.setSp_fu(pq.getSp_fuParam());    
            result.add(subscription);
        }
        return result;
    }
    
    /**
     * Adds a subcription to this entity.  
     */
    public static void addSubscription(ru.terralink.mvideo.sap.UpdateStatusSubscription subscription)
    {
        String username = ru.terralink.mvideo.sap.Mvideo5DB.getSyncUsername();    
        ru.terralink.mvideo.sap.intrnl.UpdateStatus_pull_pq  pqEntity = ru.terralink.mvideo.sap.intrnl.UpdateStatus_pull_pq.findSub(username, (java.lang.String)subscription.getSp_code(),(java.lang.String)subscription.getSp_comment(),(java.lang.String)subscription.getSp_fo(),(java.lang.String)subscription.getSp_fu());	
    	if (pqEntity == null)
        {
            pqEntity = new ru.terralink.mvideo.sap.intrnl.UpdateStatus_pull_pq();		
            pqEntity.setUsername(username);
            pqEntity.setSp_codeParam((java.lang.String)subscription.getSp_code());    
            pqEntity.setSp_commentParam((java.lang.String)subscription.getSp_comment());    
            pqEntity.setSp_foParam((java.lang.String)subscription.getSp_fo());    
            pqEntity.setSp_fuParam((java.lang.String)subscription.getSp_fu());    
          	pqEntity.save();    
        }
    }
    
    /**
     * Removes a subscription from this entity.  
     */
    public static void removeSubscription(ru.terralink.mvideo.sap.UpdateStatusSubscription subscription)
    {
        String username = ru.terralink.mvideo.sap.Mvideo5DB.getSyncUsername();
        ru.terralink.mvideo.sap.intrnl.UpdateStatus_pull_pq  pqEntity = ru.terralink.mvideo.sap.intrnl.UpdateStatus_pull_pq.findSub(username, (java.lang.String)subscription.getSp_code(),(java.lang.String)subscription.getSp_comment(),(java.lang.String)subscription.getSp_fo(),(java.lang.String)subscription.getSp_fu());	
        if (pqEntity != null)
        {
            pqEntity.delete();        
        }
    }
    
    
    
    
    /**
     * Submit pending operations of the mobile business object (ready for sending to server)  
     */
    public static void submitPendingOperations()
    {
        DELEGATE.submitPendingOperations();
    }
    
    /**
     * Cancel all the pending operations (not submitted operation).  
     */
    public static void cancelPendingOperations()
    {
        DELEGATE.cancelPendingOperations();
    }
    
    /**
     * Get the last called operation of the mobile business object  
     */
    public String getLastOperation()
    {
        if (!getCvpOperation().isNull())
        {
            com.sybase.afx.json.JsonObject cvpOperation = (com.sybase.afx.json.JsonObject)(com.sybase.afx.json.JsonReader.parse(__cvpOperation.getValue()));
            return (String)cvpOperation.get("cvp_name");
        }
        if (getPendingChange() == 'C')
        {
        }
        else if (getPendingChange() == 'D')
        {
        }
        else if (getPendingChange() == 'U')
        {
        }
        return null;
    }
    
    public ru.terralink.mvideo.sap.UpdateStatus getDownloadState()
    {
        return (ru.terralink.mvideo.sap.UpdateStatus)i_getDownloadState();
    }
    
    public ru.terralink.mvideo.sap.UpdateStatus getOriginalState()
    {
        return (ru.terralink.mvideo.sap.UpdateStatus)i_getOriginalState();
    }
    
    /**
     * Install a callback handler
     */
    public static void registerCallbackHandler(com.sybase.persistence.CallbackHandler handler)
    {
        DELEGATE.registerCallbackHandler(handler);
    }
    
    public static com.sybase.persistence.CallbackHandler getCallbackHandler()
    {
        return DELEGATE.getCallbackHandler();
    }
}